dpc-sdp/ripple

- packages/Molecules/Card/CardContent.vue
- packages/Molecules/Card/CardCta.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1111
* Fixed width of CardCTA image to 148x148.
* Implemented object-fit polyfill consistently across CardContent and CardCTA.
* Updated CardContent base polyfill to be scoped to individual image field and called only if required.
> [SDPA-1111] Update CTA card with fixed image size.

- packages/Organisms/SiteHeader/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1178
1.  Fixed IE11 alt+tab bug. Route change removes link focus.
https://drive.google.com/file/d/1YwD-T6y28t6CaMDCDmMx5tqiLXZ8gQyt/view?usp=sharing
_Video shows before and after of blur()._
Before - shows menu on alt + tab and in console the focus is on the menu link a.
After - doesn't show menu on alt + tab and focus is on body.
> [SDPA-1178] Fixed IE11 alt+tab bug. Route change removes link focus.

- packages/Atoms/Link/TextLink.vue
- packages/Molecules/RelatedLinks/index.vue
- packages/Molecules/WhatsNext/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1240
As per [comment](https://digital-engagement.atlassian.net/browse/SDPA-1240?focusedCommentId=50734&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-50734) on SDPA-1240, All external links should have an external link icon.
1.  Made RplTextLink always use external_link icon if link is external.
1.  Removed internal link icon prop on RplTextLink in RplWhatsNext and RplRelatedLinks
> [SDPA-1240] TextLink always uses external_link icon if link is external.

- packages/Atoms/Icon/Icon.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1363
1.  Changed RplIcon svg to use href instead of deprecated xlink:href attribute  - see note on https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
Tested working in Firefox mac 63.0.3
> [SDPA-1363] Removed deprecated xlink:href on svg icons.

- packages/Molecules/AnchorLinks/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-99
1.  Added checking for the anchor link element, if the array of anchor links is empty it won't render.
> [SDPSUP-99] Fixed empty anchor link section showing on Page templates

- packages/Atoms/Global/scss/settings/_button.scss
- packages/Atoms/Global/scss/settings/_color.scss
- packages/Molecules/Layout/QuickExit.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1740
1.  Updated the danger color to match Ripple Pattern Library 1.2.0
2.  Added rollover color for quick exit button. 
Hover state for quick exit
Updated danger color
> [SDPA-1740] Updated danger color and added hover color for quick exit button

- packages/Molecules/Contact/index.vue
- test/__snapshots__/storyshots.test.js.snap
1.  Adding links to the contact us block email field.
> [VICPOLUAT-117][SDPA-2049] : Adding links to the contact us block email field.

- packages/Organisms/SiteHeader/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2051
1.  Fix for ios safari issue with 100vh and the bottom bar - https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html Replaces vh with %.
> [SDPA-2051] Replace view height to fix ios safari issues.

- packages/Molecules/Card/CardEvent.vue
- packages/Molecules/Card/CardPromotion.vue
- packages/Molecules/Card/mixins/cardtrimfield.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1946
* Add checks to prevent missing link text from throwing error.
* Can occur for promotion and event cards.
* Added comment to explain purpose of getTrimFieldMaxHeightOffset function.
Looks like there are checks in the calling function to prevent a null card from being passed to the getTrimFieldMaxHeightOffset function. These issues are appear to be due to the overridden getTrimFieldMaxHeightOffset() functions in Promotions and Events not including null checks for CTA text (the 'Read More' text at the bottom of the card). If a link is defined, but the text is null, then this issue would occur.
No screenshot.
> [SDPA-1946] Add checks to prevent missing link text from throwing error.

- packages/Atoms/Global/mixins/breakpoint.js
- packages/Molecules/Card/no-ssr/CardCarousel.vue
- packages/Molecules/Card/stories.js
- src/storybook-components/Page.vue
- src/storybook-components/_data/demoData.js
- test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1900
1.  Card Carousel props added to define cards to show.
This change allows a new colsBp prop to be passed to RplCardCarousel. The colsBp matches the same way breakpoints on <rpl-col /> elements are defined. This means the same object can be used for RplCol and RplCardCarousel.
This required a change to the breakpoint mixin to expose the available breakpoints as an ordered array. This allows the card carousel to pick the largest enabled breakpoint from the list and determine how many cards to show by dividing by the total cols (a new prop as well).
> [SDPA-1900] Card Carousel props added to define cards to show.

- packages/Organisms/Markup/Markup.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1658
1.  Change selector from .rpl-markup__inner>h2:first-of-type to .rpl-markup__inner>h2:first-child
**After**
**Before**
> [SDPA-1658] Fix h2 top margin when there is something above it.

- packages/Organisms/SiteSectionNavigation/menu.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2252
1.  Headings for site section navigation are now always coloured #fff
2. Each menu level will have a left padding of its parent + 16px, up to three levels deep.
3. First level menu item now has left padding of 24px. 
4. Third menu level uses VIC-Regular font instead of VIC-Medium
Ripple component design:
Site section navigation now passes AA and AAA contrast validation:
> [SDPA-2252] Improved site section navi menu accessibility

- packages/Organisms/ImageGallery/ImageGallery.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2437
1.  Fix image gallery height in modal.
Force 100% height to override inline auto height introduced in:
https://github.com/SSENSE/vue-carousel/commit/f1e631427f533b5f7846f95fa7099abd818e1683
> [SDPA-2437] Fix image gallery height in modal.

- package-lock.json
- packages/Molecules/Layout/PageLayout.vue
- packages/Molecules/Pagination/index.vue
- packages/Molecules/Search/SearchResults.vue
- packages/Organisms/Markup/stories.js
- src/storybook-components/EventSearchPage.vue
- src/storybook-components/GrantSearchPage.vue
- src/storybook-components/SearchPage.vue
- test/__snapshots__/storyshots.test.js.snap
Make pagination in search result wrap full width and add padding-bottom to account for mobile. 
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2629
1.  Remove conditionally setting pagination steps per breakpoint (breaks in SSR - SDPA-2629)
1.  Reserve space for scroll to top to sit below pagination steps
> [SDPA-2629] Remove breakpoint mixin for pagination and set padding

- scripts/generate-readme/README_template.md
- scripts/generate-readme/generate-readme.js
- scripts/generate-readme/get-imports.js
Implements:
1. Support for linebreaks in the stories.add() feature for cases such as:
```
.add(
'Icon Library',
withReadme(readme, () => ({
components: { SIcons },
template: '<s-icons :icons="icons" :color="color" :size="size" />',
data () {
return demoData.iconLibrary()
}
}))
)
```
will output as:
```
See [Storybook/Icon Library](https://ripple.sdp.vic.gov.au/?selectedKind=Atoms/Icon&selectedStory=Icon%20Library).
```
2. Includes import statements for components defined in no-ssr/index.js files. Such as RplImageGallery and RplCardCarousel:
```
--------------------------------------------------------------------------------
import {
RplImageGalleryModal,
RplFullscreenImage
} from '@dpc-sdp/ripple-image-gallery'
import { RplImageGallery } from '@dpc-sdp/ripple-image-gallery/no-ssr' …
```
> Documentation script update.

- packages/Molecules/Card/CardNavigationFeatured.vue
- test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2632
Improved Featured Navigation card configurations.
Supports the following additional configurations:
* Image with title and no summary
* No image with title and summary
* No image with title with and no summary
> [SDPA-2632] Featured Nav improvements.

- packages/components/Molecules/Form/formAlert.vue
- packages/components/Molecules/Form/index.vue
- packages/components/Molecules/Form/stories.js
- src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1166
* Form alert content was being overridden by a v-html="" property. Message inserted within form-alert slot.
* 'Error' color is now 'Danger' - Add support for both 'danger' and 'error' variant for backwards compatibility.
* Added a storybook page to test alerts.
> [SDPA-1166] Form alerts.

- packages/components/Atoms/Icon/TextIcon.vue
- src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2945
* Use 'else' statement to avoid vue printing a  comment (and inserting an underlined space).
* Move rpl-icon property definitions into a computed value to increase code readability.
Before:
After:
> [SDPA-2945] Prevent underline from showing after the icon on a text link.

- packages/components/Organisms/SiteFooter/Acknowledgement.vue
- packages/components/Organisms/SiteFooter/stories.js
- packages/ripple-nuxt-tide/lib/pages/Tide.vue
- src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2985
* Add 'default' and 'standalone' themes to acknowledgment.
* Add styling for standalone theme.
* Add to Tide page with check on 'field_show_ack_to_country' field.
> [SDPA-2985] Prominent acknowledgment message.

- Dockerfile.app
This will allow nuxt to gracefully handle a shutdown of the container.
> AIODPC-8: Start nuxt without yarn

- packages/ripple-nuxt-tide/modules/search/lib/search/module.js
- packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/api.js
- packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/querybuilder.js
- packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3128
1.  Added a new property to the search options to exclude combinations of content-types and records with fields values from search results
> [SDPA-3128] Added property to exclude hits.

- packages/components/Molecules/Pagination/index.vue
- packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3203
1.  searchmixin 'this.pager.initialStep' value assign correction on the watch.
2. On pagination index.vue, watch for totalsteps is removed because it was changing the value of currentsteps. This will fix the issue when you are at a certain page number on a search page and refreshing the page will still be highlighting at the correct page.
> [SDPA-3203] Added pagination correct number highlighting fix.

- packages/ripple-nuxt-tide/modules/alert/plugin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3390
1.  Change in plugin.js to check for null link title and link URL. At BE we made the link field for an alert not mandatory. So there will be situations when these fields can be null.
> [SDPA-3390] Alerts with no link FE crash fix.

- packages/ripple-nuxt-tide/modules/event/pages/search.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3310
1.  Added default filter value for end date.
> [SDPA-3310] Whatson event listing filtering by end date

- packages/ripple-nuxt-tide/lib/core/mapping.js
- packages/ripple-nuxt-tide/lib/core/middleware.js
- packages/ripple-nuxt-tide/lib/server-middleware/request-log.js
- packages/ripple-nuxt-tide/lib/templates/axios.js
- packages/ripple-nuxt-tide/modules/webform/conditional-logic.js
- packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
- packages/ripple-nuxt-tide/test/unit/mapping.test.js
- packages/ripple-nuxt-tide/test/unit/webform.test.js
**JIRA issue:** 
https://digital-engagement.atlassian.net/browse/SDPSUP-1118
https://digital-engagement.atlassian.net/browse/SDPA-3400
**Github issue: **
https://github.com/dpc-sdp/ripple/issues/595
1.  Merged PR #594 for more webform conditional logic improvement
2. Updated tests for webform
3. Fixed webform and mapping error handling
> [SDPSUP-1118] [SDPA-3400]Update the webform conditional logic (#594)

- packages/components/Molecules/List/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3533
1.  Added break-word for rpl-list__text to break longer word to fit in smaller screens.
> [SDPA-3533] News info goes offscreen bug fix.

- packages/components/Molecules/ShareThis/index.vue
- src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** No ticket.
Part of the accessibility fix was setting network tag to be a button, removing the need for an inner button element. Because of this __social and __button became the same thing. __social was removed, however to avoid breaking any sites that depend on the __social class this fix will add the class name alongside __button.
> Accessibility: Social buttons to include '__social' class.

- packages/components/Molecules/Form/index.js
- packages/components/Molecules/Search/SearchForm.vue
- packages/components/Molecules/Search/stories.js
- packages/ripple-nuxt-tide/lib/pages/Tide.vue
- packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
- packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4169
* Implement custom search.
* Fix search form not correctly importing in storybook.
* Update storybook story for interactive knobs. Remove deprecated rplchecklist example.
* Add new search form theme 'solid' - set for all header embedded search forms.
* Add styling for 'solid' theme.
* encodeURIComponent will encode '+' and it will display in the search result. As encodeURIComponent handles other special characters as well, it makes sense to keep the encoding and allow it to handles spaces.
NOTE: This requires the features implemented in https://github.com/dpc-sdp/content-vic-gov-au/pull/861.
> [SDPA-4169] Custom embedded search

- packages/ripple-nuxt-tide/lib/core/tide.js
- packages/ripple-nuxt-tide/lib/module.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1668
1. Increased the timeout from 4 seconds to 10 seconds. This is to accommodate the semi-regular slow responses from downstream APIs.
See JIRA issue comments for chart showing instances of requests taking >4s.
> [SDPSUP-1668] Increased timeout to 10 seconds.

- packages/components/Molecules/Layout/QuickExit.vue
- packages/components/Organisms/ImageGallery/ImageGalleryModal.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4106
1.  Moved close button for image gallery modal from the right side to the left side to avoid overlapping with quick exit button.
2. Changed the z-index for "quick exit" to fix the IE issue. The image gallery modal z-index was higher than the "quick exit" z-index value, which was causing it to hide in IE.
!--
Provide as many screenshots as required to make reviewers understand what was changed.
-->
> [SDPA-4106] Added quickexit fix for image gallery modal and IE.

- packages/ripple-nuxt-tide/lib/core/tide-helper.js
- packages/ripple-nuxt-tide/lib/middleware/page-head.js
- packages/ripple-nuxt-tide/test/unit/tide.test.js
**JIRA issue:** Parent ticket - https://digital-engagement.atlassian.net/browse/SDPA-4457
Subtask - https://digital-engagement.atlassian.net/browse/SDPA-4466
The grant nodes that get created during the feed, should not be indexed by google and also shouldn't get added to the sitemap.
1. Added robotsMeta in the page-head.js to capture the robot's meta content from BE.
2. Added robotsMeta in tide-helper.js to render it the page header if it exists.
FE PR Env link - ([Click Here](https://app-ripple-pr-731.lagoon.vicsdp.amazee.io/))
BE PR - https://github.com/dpc-sdp/tide_grant/pull/5
Content-vic PR for testing - https://github.com/dpc-sdp/content-vic-gov-au/pull/908 ([Env Link](https://nginx-php-content-vic-pr-908.lagoon.vicsdp.amazee.io/))
When there is robot content - 
When there is no …
> [SDPA-4466] Added new var to capture robots meta from page header.

- packages/components/Molecules/Form/Fieldset.vue
- packages/components/Molecules/Form/__snapshots__/stories.storyshot
- packages/components/Molecules/Form/index.vue
- packages/components/Molecules/Form/stories.js
- packages/components/Organisms/Markup/Markup.vue
- packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4513
1.  Changed previous form max width global style to be conditional. Added a new prop "fullWidth" for Ripple Form to control the width. By default it's set to `true`. If it's `false`, global max width limit for content will be applied.
2. Disabled "fullWidth" for embedded webform.
3. Added missing knobs for Ripple form in Storybook.
> [SDPA-4513] Fixed search filter form width

- packages/components/Atoms/ResponsiveImg/ResponsiveImg.vue
- packages/components/Atoms/ResponsiveImg/__snapshots__/stories.storyshot
- packages/components/Molecules/Card/__snapshots__/stories.storyshot
- packages/components/Molecules/Search/__snapshots__/stories.storyshot
- packages/components/Organisms/CallToAction/__snapshots__/stories.storyshot
- packages/components/Organisms/CallToAction/index.vue
- packages/components/Organisms/CallToAction/stories.js
- packages/components/Organisms/CampaignSecondary/__snapshots__/stories.storyshot
- packages/components/Organisms/Event/__snapshots__/stories.storyshot
- packages/components/Organisms/News/__snapshots__/stories.storyshot
1.  Change Call to Action component to contain images instead of cover.
1. Add max height variable `$rpl-call-to-action-image-max-height` for CTA image height - set to 400px default to control massive images
**XL**
**L**
**M**
**S**
**XS Mobile**
> [SDPA-4624] Change CTA img fit to contain

- packages/components/Organisms/SiteHeader/__snapshots__/stories.storyshot
- packages/components/Organisms/SiteHeader/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-587
Update dividers in site header between menu / vic logo / co-brand logo.
- Logo now sits centred.
- Added div element dividers between menu / vic logo / cobrand logo, removing the right border / padding / margin implementation.
The new implementation means keyboard focus outlines no longer wrap around divider elements and provides more sub-site styling options.
Supports:
- Vic + Co-brand Logo
- Vic only logo
- Co-brand only logo
- Neither logo
> Site Header Dividers and Focus outline improvements.

- packages/ripple-nuxt-tide/lib/config/defaults.js
- packages/ripple-nuxt-tide/lib/core/tide.js
- packages/ripple-nuxt-tide/lib/templates/axios.js
- packages/ripple-nuxt-tide/test/unit/tide.test.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4934
Server will die by a lot `ERROR  Failed to get next page data` like below:
```
2021-01-12 01:07:16 [Connect]  INFO  Proxy GET request to https://content.vic.gov.au//api/v1/taxonomy_term/sites , res status code: 200. {"service":"ripple-tide","requestQuery":"site=4","requestId":"7431e551512d0d860a1cc2826797a0b0"}
--
  | 2021-01-12 01:07:17 [Tide]  ERROR  Failed to get next page data
  | TypeError: Cannot read property 'includes' of undefined
  | at module.exports.$axios.onError.error (server.js:20448:38)
  | at interceptors.response.use.error (server.js:20070:56)
  | at process._tickCallback (internal/process/next_tick.js:68:7) {"service":"ripple-tide"}
  | 2021-01-12 01:07:17 [Tide]  ERROR  Failed to get next page …
```
> [SDPA-4934] Added error handling for invalid paginated api response

- packages/components/Organisms/HeroBanner/HeroBanner.vue
- packages/components/Organisms/HeroBanner/heroBanner.stories.mdx
- packages/ripple-nuxt-tide/lib/middleware/banners.js
Allow alt text to be displayed for hero banner logos (primarily for screen readers).
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6333
This update displays the logo's alt title in the hero component, this means the logo being passed to `HeroBanner.vue` is now an object instead of a string.
The storybook story has been updated so the logo prop is now an object. https://storybook.pr-1228.ripple.sdp2.sdp.vic.gov.au/?path=/story/organisms-banners--hero-banner
The change can be previewed at the below URLS:
Hero logo with alt text:  https://app.pr-1228.ripple.sdp2.sdp.vic.gov.au/sdpta-all-components-landing-page-fixture
Page with no hero logo:  https://app.pr-1228.ripple.sdp2.sdp.vic.gov.au/embedded-video-test
> [SDPAP-6333] Added alt text to hero banner logos.

- packages/ripple-nuxt-tide/modules/landing-page/components/CardCollection.vue
- packages/ripple-nuxt-tide/modules/landing-page/lib/card-collection-utils.js
- packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
- packages/ripple-nuxt-tide/modules/landing-page/tide.middleware.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SW-1635
1. Migrate patch from solar website: https://github.com/dpc-sdp/solar-vic-gov-au/blob/develop/patches/%40dpc-sdp%2Bripple-nuxt-tide%2B1.29.2.patch
2. Update to card collection to address the following:
* Custom no results message not displaying
* Results not hidden when minimum number of cards isn't meet
* Component isn't hidden when minimum number of cards isn't meet and hide component is set
For reference, the deprecated drupal fields: https://github.com/dpc-sdp/tide_automated_listing/blob/dda418f23871f2c4a1cf1ef25a71d442a1f28da3/src/Plugin/Field/FieldWidget/AutomatedListingConfigurationWidgetEnhanced.php#L541
Compare the display of the following develop page vs the same page on the PR branch.
**Develop**: …
> [SW-1635] update card collection component

- .lagoon.yml
Removes reference site hostnames from .lagoon.yml so they can be added to the actual reference site.
> [DDS-1368] Removed reference site hostnames from ripple project.

- packages/components/Molecules/Form/index.vue
- packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7784
Fields were being cleared when the clear form button is pressed but the actually form state isn't returned to it's initial state, i.e. with conditional logic applied.
Let me know if anyone's got some suggestions to avoid using `this.$refs.vfg.$forceUpdate()`.
> [SDPAP-7784] reset forms conditional state after clearing the form 

- packages/ripple-nuxt-tide/lib/layouts/default.vue
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7958
1. Any in page nav item that started with a number would break the page once clicked and refreshed, shared or opened in a new tab (on solar vic), this was due to the fact that IDs starting with a numbers make for an invalid selectors
> [SDPAP-7958] fix for in page nav links breaking on refresh/share

- .github/workflows/build.yml
- .github/workflows/canary-npm-release.yml
- .github/workflows/commit.yml
- .github/workflows/create-release.yml
- .github/workflows/nightwatch.yml
- .github/workflows/publish-to-npm.yml
- .github/workflows/tag-release.yml
- .github/workflows/test.yml
- scripts/trigger-e2e.sh
**JIRA issue:** https://salsadigital.atlassian.net/browse/DEVOPS-248
1. Created new Github action workflows based off current CircleCI implementation
- Tested Github action workflow commit
> [DEVOPS-248] Migrate CircleCI to Github actions

- .github/workflows/nightwatch.yml
- scripts/trigger-e2e.sh
1. Updated the nightwatch workflow input names to match what the estuary API expects to send to the GitHub workflows.
https://github.com/dpc-sdp/estuary/blob/79da49c5866435436a14795c288fc8a9a2cceaa4/pkg/github/server.go#L53
2. Removed `E2E` input and logic
3. Updated `trigger-e2e.sh` script to use the Estuary app to trigger e2e testing.
> Updated nightwatch workflow inputs and added Estuary app to trigger workflow

- .github/workflows/e2e.yml
- examples/reference/nuxt.config.js
1. Removed the backend regression
2. Updated regression testing jobs
> updated the ripple regression test
