.lagoon.yml
removed the task to post the commit to wiki
=> removed that task to post to wiki

README.md, package-lock.json, packages/Atoms/Global/components/Divider.vue, packages/Atoms/Global/index.js, packages/Atoms/Global/scss/_global.scss, packages/Atoms/Global/stories.js, packages/Molecules/Pagination/index.vue, packages/Molecules/Pagination/stories.js, packages/Molecules/Search/SearchForm.vue, packages/Molecules/Search/SearchResult.vue, packages/Molecules/Search/SearchResults.vue, packages/Molecules/Search/index.js, packages/Molecules/Search/stories.js, src/storybook-components/Page.vue, src/storybook-components/README.md, src/storybook-components/SearchPage.vue, src/storybook-components/_data/demoData.js, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-835
1.  Added divider component in global
2. Added search results component for wrapping search results elements
3. Added search page template demo
=> [SDPA-835]  Search fix

packages/Molecules/Layout/PageLayout.vue, packages/Molecules/Layout/stories.js, src/storybook-components/CampaignPage.vue, src/storybook-components/SiteLayout.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-865
1.  Fix: Allow undefined backgroundImage on PageLayout.
No change from existing implementation. This is a fix to invalid HTML.
=> [SDPA-865] Fix: Allow undefined backgroundImage on PageLayout.

packages/Atoms/Global/README.md, packages/Molecules/Card/CardContent.vue, packages/Molecules/Card/CardCta.vue, packages/Molecules/Card/README.md, packages/Molecules/Card/ReadmeCardContent.md, packages/Molecules/Card/index.js, packages/Molecules/Card/stories.js, packages/Molecules/Search/README.md, src/storybook-components/Page.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-792
1. Added CardContent updates from SDPA-614 branch (https://github.com/dpc-sdp/ripple/pull/61)
2. Added Card CTA.
3. Updated docs / tests.
=> [SDPA-792] card cta

.npmrc, Dockerfile, Dockerfile.local, Dockerfile.test, README.md
1.  Changed deployment to use `npm ci` instead of `npm install`.
=> Fixed lagoon npm install error

packages/Organisms/SiteFooter/index.vue, packages/Organisms/SiteFooter/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-923
1.  Added multiple logos to footer.
=> [SDPA-942] logos for footer

package-lock.json, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-989
From https://github.com/dpc-sdp/museum-vicpol-vic-gov-au/pull/42
- Added number field
- Added hint
- Changed hint positon to follow vicgov digital standards
=> [SDPA-997] Added vicpol form changes

packages/Organisms/HeroBanner/IntroBanner.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1012
1.  bug fix for `[Vue warn]: Property or method "theme" is not defined on the instance but referenced during render. `
=> [SDPA-1012] Fixed error of undefined prop

packages/Organisms/Event/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1038
1.  Updated repository reference for Event package.
=> [SDPA-1038] Updated repo for Event package.

packages/Molecules/Card/CardEvent.vue, packages/Molecules/Card/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1119
1.  Removed topic from CardEvent.
=> [SDPA-1119] Removed topic from CardEvent.

package-lock.json, package.json, packages/Molecules/Alert/.npmignore, packages/Molecules/Alert/Alert.vue, packages/Molecules/Alert/AlertBase.vue, packages/Molecules/Alert/LICENSE, packages/Molecules/Alert/README.md, packages/Molecules/Alert/index.js, packages/Molecules/Alert/package.json, packages/Molecules/Alert/stories.js, src/storybook-components/Page.vue, src/storybook-components/_data/demoData.js, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-636
1.  Added Alert package and AlertBase component.
2. Have added the Alert component as a placeholder. It is not fully functional and has a separate ticket (https://digital-engagement.atlassian.net/browse/SDPA-27).
=> [SDPA-636] Added Alert package and AlertBase component.

packages/Molecules/Card/CardEvent.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-SDPA-1119
1.  Removed stray topic variable call.
No screenshot.
=> [SDPA-1119] Removed stray topic variable call.

packages/Atoms/Global/mixins/cardtrimfield.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1155
1.  Fixed `card.querySelector is not a function error`
=> [SDPA-1155] Fixed card.querySelector is not a function error

package-lock.json, packages/Molecules/Card/CardEvent.vue, packages/Molecules/Card/CardKeydates.vue, packages/Molecules/Card/CardPromotion.vue, packages/Molecules/Card/mixins/cardtrimfield.js, packages/Molecules/Card/no-ssr/CardCarousel.vue, packages/Molecules/Card/package.json, src/storybook-components/PageCardTrim.vue, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1160
1.  Moved cardtrimfield from global to the Card package.
2. Added fontfaceobserver for checking on font loading (dependency of card).
3. Updated cardtrimfield to take an event object and update on 'setTrimFieldMaxHeight' event.
4. Updated cardtrimfield to optionally disable window resize updates (for when updates are handled externally).
5. Updated carousel to invoke trim updates on unique vue-carousel DOM attribute changes.
6. Added page for testing the trim functions in Template/Page with trim cards.
7. Corrected class name of 'rpl-card-keydates'.
=> [SDPA-1160] Updated card trimming to refresh more often.

packages/Molecules/Search/SearchForm.vue, packages/Organisms/SiteHeader/search.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-925
1.  Updated search icon, text and input box alignment.
=> [SDPA-925] Updated search icon, text and input box alignment.

packages/Molecules/Sitemap/index.vue, src/storybook-components/PageSitemap.vue, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1198
1.  Added mobile padding to sitemap component.
=> [SDPA-1198] Added mobile padding to sitemap component.

package-lock.json, package.json, packages/Molecules/Timeline/.npmignore, packages/Molecules/Timeline/LICENSE, packages/Molecules/Timeline/README.md, packages/Molecules/Timeline/Timeline.vue, packages/Molecules/Timeline/index.js, packages/Molecules/Timeline/package.json, packages/Molecules/Timeline/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-765
1.  Added timeline component.
=> [SDPA-765] Added timeline component.

packages/Organisms/UpdatedDate/index.vue, src/storybook-components/Page.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1244
1.  Added mobile padding to RplUpdatedDate
=> [SDPA-1244] added mobile padding to RplUpdatedDate

packages/Molecules/Search/SearchForm.vue, src/storybook-components/Page.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-642
https://digital-engagement.atlassian.net/browse/SDPA-934
- Changed top/bottom spacing
- Changed bottom line height
- Added a demo for landingpage
=> [SDPA-642] [SDPA-934] Updated spacing of search form

.storybook/config.js, packages/Molecules/Timeline/Timeline.vue, packages/Organisms/News/NewsListing.vue, src/storybook-components/Page.vue, src/storybook-components/scss/story.scss, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-348
1. Fixed spacing for news listing
2. Fixed spacing for timeline
3. Added storybook vue info background color for inspect the spacing
=> [SDPA-348] news listing padding

package-lock.json, packages/Molecules/Search/SearchResults.vue, packages/Molecules/Search/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
1.  Added support for RplCardPromotion to RplSearchResults
=> Added support for RplCardPromotion to Search Results.

packages/Organisms/ImageGallery/ImageGallery.vue, packages/Organisms/ImageGallery/ImageGalleryModal.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1024
1. Updated image gallery to display nav in mobile.
2. Fixed an issue with 100vh and horizontal scrollbars causing inconsistency in placement of mobile nav arrows.
=> [SDPA-1024] Updated image gallery to display nav in mobile.

packages/Molecules/Layout/QuickExit.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1249
1.  Updated quick exit z-index to make sure it on top of nav modal window
=> [SDPA-1249] Updated quick exit z-index

package-lock.json, packages/Atoms/Global/index.js, packages/Atoms/Icon/Icon.vue, src/storybook-components/Page.vue, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1249
1. Fixed bug for icon disppearing on ios.
2. Changed quick exit default from show to hide.
=> [SDPA-1249] Fixed icon and quick exit issues

packages/Molecules/Form/fields/fieldRplslider.vue, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-787
1.  Added slider field.
=> [SDPA-787] slider field

package-lock.json, packages/Atoms/Global/utils/helpers.js, packages/Molecules/List/index.vue, packages/Molecules/Search/SearchResults.vue, packages/Molecules/Search/stories.js, packages/Organisms/Grants/GrantsListItem.vue, packages/Organisms/Grants/GrantsOverview.vue, packages/Organisms/Grants/index.js, src/storybook-components/GrantSearchPage.vue, src/storybook-components/_data/demoData.js, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1488
1.  [SDPA-1488] Added GrantsListItem component for use in search results
1.  Refactored RplSearchResults to dynamically import search result component type
1.  [SDPA-1496] Changed funding to be a range instead of single value.
1.  Added link prop to RplList to optionally make list title a link.
=> [SDPA-1488] Adds grant overview list item.

README.md, packages/Molecules/Form/Checkbox.vue
**JIRA issue:** NO TICKET
1.  Fix some linting issues.
2. Fix spelling in Readme.
NO SCREENSHOT
=> Fix some linting issues. Fix spelling in Readme.

Dockerfile
upgrade node from version 8 to version 10
=> upgrade node from version 8 to version 10

packages/Molecules/Layout/BaseLayout.vue, packages/Molecules/Layout/PageLayout.vue, packages/Organisms/HeroBanner/HeroBanner.vue, packages/Organisms/HeroBanner/IntroBanner.vue, src/storybook-components/CampaignPage.vue, src/storybook-components/EventSearchPage.vue, src/storybook-components/GrantSearchPage.vue, src/storybook-components/Page.vue, src/storybook-components/PageCardTrim.vue, src/storybook-components/PageForm.vue, src/storybook-components/PageHeroGraphics.vue, src/storybook-components/PageSitemap.vue, src/storybook-components/SearchPage.vue, src/storybook-components/SiteLayout.vue, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1324
1. Updated PageLayout to avoid clipping dropdowns.
2. Updated PageLayout to not use a rpl-container (contained overflow: hidden).
3. Created a test page for checking dropdowns in Ripple.
4. Fix HeroBanner / Intro Banner to use grid components.
5. Remove rpl-container (hidden overflow) from pages.
6. Add overflow to the site-layout.
=> [SDPA-1324] dropdown truncation

packages/Molecules/Contact/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1372
1.  Changed rpl-contact phone numbers to an array of objects to allow adding a title to numbers seperate to tel link.
=> [SDPA-1623] Changed phone number in rpl-contact to object to add title.

packages/Molecules/Pagination/index.vue, packages/Molecules/Search/stories.js, src/storybook-components/SearchPage.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1205
1. Reset pagination arrow on totalStep change.
2. Update Search Page to allow for testing.
3. Remove unused property from Search Results story.
=> [SDPA-1205] Reset pagination arrow on totalStep change.

packages/Atoms/Global/scss/settings/_color.scss, packages/Organisms/SiteHeader/index.vue, packages/Organisms/SiteHeader/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/projects/SDPAPC/issues/SDPAPC-3
1. Added boolean `showLogout` prop to `RplSiteHeader`
2. This conditionally renders a logout button in the header
3. When the button is clicked `RplSiteHeader` emits a `logout` event to be consumed
=> [SDPAPC-3] Added logout button to site header.

packages/Organisms/CampaignPrimary/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-49
1.  Added a new CSS rule to CampaignPrimary to allow mouse clicks on `.rpl-campaign-primary__primary_arrow` to fall through to the `a href` element below.
=> [SDPSUP-49] Fixed CampaignPrimary arrow not acting as hyperlink

packages/Molecules/Form/fields/fieldRplmarkup.vue, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1622
1.  VFG RplMarkup field added.
=> [SDPA-1622] VFG RplMarkup field added.

package-lock.json, packages/Molecules/Search/package.json, packages/Organisms/SiteHeader/index.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-559
1.  Added vue-focus trap package
2. Added focus trap to site header menu, so that tabbing is kept within open menu.
=> [SDPA-559] Adds focus trap to open site header menu.

packages/Molecules/Form/Checkbox.vue, packages/Molecules/Form/fields/fieldRpldatepicker.vue, packages/Molecules/Form/formPikaday.vue, src/storybook-components/PageForm.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1727
1.  Fixed checkbox.
2. Fixed dates.
3. Updated Form page to test.
Following error should not show for required checkboxes:
=> [SDPA-1727] Form fixes.

packages/Organisms/CampaignPrimary/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-39
1.  Changed SCSS for `.rpl-campaign-primary` to prevent overlapping with main header and make it stay in the second section at the medium breakpoint.
=> [SDPSUP-39] Fixed unresponsive breakpoint on CampaignPrimary banner.

package-lock.json, packages/Molecules/Form/index.vue, packages/Molecules/Form/package.json, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1691
1.  Calls validate() method on vfg in onSubmit handler
1.  Adds scrollTo back 🤦‍♂️ and scrolls into view first element with error
=> [SDPA-1691] Calls validate form on submit and before submission

packages/Molecules/Form/index.vue, packages/Molecules/Form/package.json, packages/Molecules/Search/package.json
=> Fixes to form implementation.

package-lock.json, packages/Atoms/Icon/README.md, packages/Atoms/Icon/TextIcon.vue, packages/Atoms/Icon/stories.js, packages/Molecules/Form/README.md, packages/Molecules/Form/index.vue, packages/Molecules/Form/package.json, packages/Molecules/Search/package.json, packages/Organisms/Markup/README.md, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1678
1.  Fixed the regex in text icon so it can support special chars now.
2. Added the missing storybook demo for text icon.
=> [SDPA-1678] Fixed the regex issue

package-lock.json, packages/Molecules/Form/fields/fieldRplchecklist.vue, packages/Molecules/Form/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1787
1.  Removes vue-click-outside from fieldRplChecklist (seems to cause issues with re-render loop, will add back when we can look into the issue in more depth)
=> [SDPA-1787] removes vue-click-outside directive

packages/Atoms/Global/scss/settings/_color.scss, packages/Organisms/SiteHeader/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1780
1.  As this colour for logout is not defined in the SDP pattern lib colour palette, remove it from the color map and use local color var to replace it.
=> [SDPA-1780] Removed undesigned color name

test/package-version.test.js
**JIRA issue:** None
1.  Add a test to check versions of packages against the lerna version.
None
=> Add a test to check versions of packages against the lerna version.

package-lock.json, packages/Molecules/Form/fields/fieldRplchecklist.vue, packages/Molecules/Form/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1789
1.  Adds vue-on-click-outside to close rplchecklist on click outside
=> [SDPA-1789] Adds vue-on-click-outside to close rplchecklist on click outside

packages/Molecules/Form/Checkbox.vue, packages/Molecules/Form/fields/fieldRplclearform.vue, packages/Molecules/Form/fields/fieldRpldatepicker.vue, packages/Molecules/Form/fields/fieldRplselect.vue, packages/Molecules/Form/formPikaday.vue, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1769
1.  Adds rplClearsearch field to clear form data
1.  Refactors rplCheckbox to use computed value instead of watchers
1.  Adds watchers to RplSelect and RplDatepicker to reset on null value 
Note: Does not implement inline formatting with submit button. I feel like this should be part of the implementation of the form to keep this field reusable.
=> [SDPA-1769] Clear search form button

packages/Molecules/Form/Fieldset.vue, packages/Molecules/Form/fields/fieldRplclearform.vue, packages/Molecules/Form/fields/fieldRplselect.vue, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1762
1.  Adds RplFieldset component to encapsulate fieldset wrapper and grid.
1. Adds example story for using grouped fields and nested object for address component (see form story)
=> [SDPA-1762] Adds RplFieldset component, adds grouped fields stories.

packages/Molecules/Form/formPikaday.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1809
1.  Added icon to formPikaday element.
=> [SDPA-1809] Added icon to formPikaday element.

packages/Organisms/Grants/GrantsOverview.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1812
1. Adds RplMarkup to RplGrantsOverview to process wysiwyg field.
=> [SDPA-1812] Implemented RplMarkup  for GrantsOverview description.

packages/Organisms/Markup/Markup.vue, packages/Organisms/Markup/markup-transpiler.js
1.  Changed markuptranspiler export to default export needed for https://github.com/dpc-sdp/vic-gov-au/pull/446
=> Adds default export for markuptranspiler

packages/Molecules/Card/CardCta.vue, packages/Molecules/Card/CardHonourRoll.vue, packages/Molecules/Timeline/Timeline.vue, packages/Organisms/Profile/ProfileHighlight.vue, packages/Organisms/Profile/ProfileHighlightHonourRoll.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** No ticket
* Fix image height to 156px on profile highlight.
* Use provided object-fit mixin to ensure IE compatibility.
* Fix - ensure space between label and value is not lost in Nuxt. 
No screenshot.
=> Profile Highlights Honour Roll fixes for Nuxt implementation.

packages/Molecules/Form/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1000
* Auto Update loading animation works with groups.
* Triggers just before async call.
=> [SDPA-1000] QA Fixes

packages/Molecules/Form/index.vue, packages/Molecules/Form/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1697
1.  Adds optional form title.
=> [SDPA-1697] Adds optional form title.

packages/Atoms/Link/TextLink.vue, packages/Molecules/RelatedLinks/index.vue, packages/Organisms/HeroBanner/HeroBanner.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-698
1.  Link icon was removed from related links.
2. Added support in rpl-text-link for small and large underlines. Underline size follows size of text-link. 
3. Large text link underlines are 3px tall, while small text link underlines are 2px tall.
=> [SDPA-698] Removed link icon from related sites and added support for small and large underlines

.storybook/config.js, packages/Atoms/Button/stories.js, src/storybook-components/scss/story.scss, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1918
1.  Added example for button with click event action
2. Moved storybook panel from bottom to right to make story more readable
3. Experimental move readme from panel tab to main story area under vue info, to make better doc layout.
=> [SDPA-1918] Added button event example with storybook layout changes

packages/Molecules/Form/Fieldset.vue, packages/Molecules/Form/fields/fieldRplclearform.vue, packages/Molecules/Search/SearchForm.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1668
Changes to Searchform to support honor roll listing
1.  Adds optional subtitle to searchForm
1.  Adds prop to control whether search field appears
1.  Adds props to control whether filters are expanded by default
1.  Removes two column styling - use `rpl-fieldset` and `form-group--two-col` instead
1.  Clearform resets array values back to empty arrays, makes working with tidesearch easier
=> [SDPA-1668] Adds props to show filterform on load and styling for honor roll

packages/Atoms/Global/scss/components/_button.scss, packages/Atoms/Global/scss/tools/_layout.scss, packages/Molecules/Card/CardContent.vue, packages/Molecules/Card/CardNavigationFeatured.vue, packages/Molecules/Card/no-ssr/CardCarousel.vue, packages/Molecules/Contact/index.vue, packages/Molecules/DocumentLink/DocumentLink.vue, packages/Molecules/Form/index.vue, packages/Molecules/Layout/PageLayout.vue, packages/Molecules/Pagination/index.vue, packages/Molecules/RelatedLinks/index.vue, packages/Molecules/Search/SearchResult.vue, packages/Molecules/Search/SearchResults.vue, packages/Molecules/ShareThis/index.vue, packages/Molecules/Sitemap/index.vue, packages/Molecules/Timeline/Timeline.vue, packages/Molecules/WhatsNext/index.vue, packages/Organisms/CampaignPrimary/index.vue, packages/Organisms/CampaignSecondary/index.vue, packages/Organisms/Grants/GrantsListItem.vue, packages/Organisms/Grants/GrantsOverview.vue, packages/Organisms/ImageGallery/ImageGallery.vue, packages/Organisms/Markup/Markup.vue, packages/Organisms/News/NewsListing.vue, packages/Organisms/Profile/ProfileHighlightHonourRoll.vue, packages/Organisms/UpdatedDate/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1810
* Set mobile gutter on site_constrain & remove from components
* Remove background white on sidebar when on mobile (gutter causes this not look good).
* Campaign Primary is the exception - add negative gutter on image to set full width.
* Remove unused variables from SCSS.
* For cards, side nav, buttons - show border-radius / borders on mobile.
(This is a ripple ticket, but was checked on Nuxt)
=> [SDPA-1810] Set mobile gutter on site_constrain & remove from components

packages/Atoms/Global/scss/tools/_layout.scss
**JIRA issue:** No ticket
1.  Edge layout to touch browser edge on mobile.
No Screen
=> Edge layout to touch browser edge on mobile.

packages/Molecules/Alert/Alert.vue, src/storybook-components/_data/demoData.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1537
1.  Fixed missing icon and background for lightning alert
=> [SDPA-1537] Fixed missing icon and background for lightning alert

packages/Organisms/SiteSectionNavigation/menu.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1821
1.  Third level items are indented from the left, to create visual differentiation from second level items
1.  Adjustment in colour of lines dividing items - these now utilise the core colour palette
1.  Font change - use 'Medium' weight for all text
=> [SDPA-1821] Styling revisions to sidebar menu.

package-lock.json, packages/Molecules/List/index.vue, packages/Molecules/List/stories.js, packages/Organisms/Grants/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1992
* Replaced RplLink with RplTextLink in RplList.
* Update stories to allow links to be tested in Storybook.
=> [SDPA-1992] Added RplTextLink to RplList.

packages/Molecules/DocumentLink/DocumentLink.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1759
1.  Changed download attr value to empty string instead of true, so file name won't be rename.
=> [SDPA-1759] Fixed doc link download name issue

packages/Molecules/Form/Fieldset.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2002
1.  Add fix for columns in ie11
=> [SDPA-2002] Fix for ie11 not recognising calc in flex shorthand.

packages/Atoms/Global/scss/generic/_global.scss, packages/Atoms/Link/TextLink.vue, packages/Molecules/Card/CardNavigationFeatured.vue, packages/Molecules/Contact/index.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2024
Fixes for some issues that are causing html markup to not validate
1.  Remove invalid font-smoothing rule (its vendor specific)
1.  Fix misspelled border-bottom-wdith rule
1.  Fix margin-bottom having too many values
1.  Fix anchor telephone links having spaces in it
=> [SDPA-2024] Fix validation errors

package-lock.json, packages/Molecules/ShareThis/index.vue, packages/Molecules/ShareThis/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2011
1.  Update vue-social-sharing to v2.4.1 with fix for https://github.com/nicolasbeauvais/vue-social-sharing/issues/123 
1.  Change import to import src directly as 2.4.1 wasn't built properly (see issue above)
=> [SDPA-2011] Update vue-social-sharing with fix for facebook sharing.

packages/Molecules/Card/CardContent.vue, packages/Molecules/Card/CardHonourRoll.vue, packages/Molecules/Card/ReadmeCardContent.md, packages/Molecules/Card/stories.js, src/storybook-components/PageCards.vue, src/storybook-components/_data/demoData.js, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1976
1.  Added 'center' prop to Card Content, and applied in Honour card (when no image).
=> [SDPA-1976] Card details centred

packages/Molecules/Form/fields/fieldRplsubmitloader.vue, packages/Molecules/Form/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2078
1.  Use loading event for show/hide submit loader. Fixes issue where rplSubmitloader would still spin if clearFormOnSuccess === false.
1.  Removes redundant methods for identifying and updating rplsubmitloader
=> [SDPA-2078] Use loading event for show/hide submit loader.

packages/Molecules/Form/fields/fieldRplchecklist.vue, packages/Molecules/Form/fields/fieldRplselect.vue, packages/Molecules/Form/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1870
1.  Makes fieldRplSelect set default value if it has been set in the model.
1.  Fix height on select field.
1.  Moved mounted hook in fieldRplchecklist to top for better readability.
=> [SDPA-1870] Fill select fields on load if the model already has a value.

packages/Molecules/Form/index.vue, packages/Molecules/Search/SearchForm.vue, src/storybook-components/_data/demoData.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2106
1.  Clear search term on clearform event.
=> [SDPA-2106] Clear search term on clearform event.

package-lock.json, packages/Molecules/ShareThis/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1941
1.  Updates vue social sharing to patched version 4.2.2 with fix for facebook issue and potentially IE issue SDPA-1941 (needs test in nuxt).
=> [SDPA-1941] Updates vue social sharing to patched version.

packages/Molecules/Search/SearchResults.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-776
1.  Set pagination size as per card column breakpoint sizes.
=> [SDPA-776] Pagination width to match cards

packages/Molecules/Layout/PageLayout.vue, packages/Molecules/Layout/index.js, packages/Organisms/SiteHeader/index.vue, packages/Organisms/SiteHeader/menu.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1517
1.  Insert quickexit into menu and remove from body if menu open
**Mobile**
**iPad**
**Desktop**
=> [SDPA-1517] Insert quickexit into menu and remove from body if menu open

packages/Atoms/Global/mixins/ProvideChildCols.js, packages/Molecules/Card/no-ssr/CardCarousel.vue, packages/Molecules/Card/stories.js, src/storybook-components/Page.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2187
1.  Implement an interface for defining child column breakpoints
=> [SDPA-2187] Implement an interface for defining child column breakpoints

packages/Atoms/Link/Link.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2188
1.  Clicking an active (current path) link will reload the page.
No screenshot.
=> [SDPA-2188] Clicking an active (current path) link will reload the page.

packages/Molecules/Layout/BackToTop.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1896
1.  Removed the button container block by set height to 0. And adjustment of position.
=> [SDPA-1896] Fixed back to top style

packages/Molecules/Search/SearchResults.vue, src/storybook-components/EventSearchPage.vue, src/storybook-components/GrantSearchPage.vue, src/storybook-components/SearchPage.vue, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2231
1.  Add childColsBp to Search Results component.
=> [SDPA-2231] Add childColsBp to Search Results component.

packages/Molecules/Sitemap/index.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2257
1.  Added h1 element to sitemap page.
2. Reduced level 0 sitemap menu item to font size 20px
3. Reduced level 0 sitemap menu item to line height 24px
Ripple Component Design for h1 element and level 0 menu size changes:
=> [SDPA-2257] Added h1 element to sitemap page

packages/Molecules/Search/SearchForm.vue, packages/Molecules/Search/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2273
These are the changes required to support the Data.vic CKAN search form.
* New props to allow Search buttons and labels to be customized.
* Allow Search button to display text beside magnifying glass.
* Added more knobs to storybook - allows testing all props for Search Form.
=> [SDPA-2273] Update Search Form features.

packages/Atoms/Link/Link.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2188
1.  Changed originalTarget to target to support Chrome / Safari.
No screens.
=> [SDPA-2188] Added fix for Webkit browsers.

packages/Molecules/Form/fields/fieldRplchecklist.vue, packages/Molecules/Form/package.json, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** No ticket
These are the changes required to support the Data.vic CKAN search form.
* Add single select option to form rplchecklist.
=> Add single select option to RplChecklist

packages/Molecules/Search/SearchResults.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2281
1.  Allow spacing on search results pagination for back to top button.
=> [SDPA-2281] Allow spacing on pagination for back to top button.

package-lock.json, packages/Molecules/Card/package.json, packages/Organisms/ImageGallery/package.json, test/__snapshots__/storyshots.test.js.snap
1.  Updates vue-carousel to latest version to resolve nuxt project conflict with upstream packages (vue-router and vuex)
=> Update vue-carousel deps

packages/Organisms/ImageGallery/ImageGallery.vue
1.  Change `align-content` value from `start` to `flex-start`. `start` not supported in ie https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#Browser_compatibility
=> Fix sass lint issue in rpl-image-gallery

packages/Organisms/SiteFooter/FooterNavigation.vue
1.  Imports default export if ES module 
1.  Adds check for whether module is already imported
=> Fix for masonry layout importing either amd or es module

packages/Molecules/Form/formAlert.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1957
1.  Moved icon, color and classes data to computed values. They were previously only being updated when the component was created, and hence would not change if the validation failed and then was successful.
=> [SDPA-1957] Makes form alert reactive to variant prop.

package-lock.json
=> Release alpha 68

packages/Molecules/Search/SearchResults.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2329
1.  Add key to sear results to fix https://digital-engagement.atlassian.net/browse/SDPA-2313
=> [SDPA-2329] Add key to search result

packages/Organisms/SiteHeader/index.vue, packages/Organisms/SiteHeader/menu.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2230
1.  IE11 fix for wrapping in Site Header.
Before change:
After change:
After change with same data from https://fvrim.vic.gov.au/:
=> [SDPA-2230] IE11 menu wrap

package-lock.json, package.json, packages/Atoms/Button/__tests__/button.test.js
1.  Adds vue test utilities to allow unit testing components
=> Adds vue test utilities

package-lock.json, packages/Molecules/ShareThis/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1941
1.  Use forked version of vue-social-sharing to fix IE issue - https://github.com/nicolasbeauvais/vue-social-sharing/issues/130 NOTE : If https://github.com/nicolasbeauvais/vue-social-sharing/pull/131 is merged we need to update this again to use updated version.
=> [SDPA-1941] Use forked version of vue-social-sharing to fix IE issue.

packages/Organisms/SiteHeader/menu.vue
1.  Only add quick exit in the one place in menu
1.  Fix check for level depth
1.  Add variable for padding
=> [SDPA-2375] Fix issue where quick exit was appearing for each menu level

package-lock.json
=> Update to alpha 69

packages/Molecules/ShareThis/index.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1584
1.  Adds semantic markup for Share This component to enable keyboard control.
1.  Adds optional prop to define aria-label (or 'Social networks' if not defined)
=> [SDPA-1584] Adds semantic markup for Share This.

packages/Molecules/AnchorLinks/index.vue
**Issue:** #329 
1.  Made Anchor Links theme vars into defaults.
=> [#329] Made Anchor Links theme vars into defaults.

packages/Molecules/Pagination/index.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1604
1.  Give pagination navigation role
1.  Set aria-current="page" on active item
1.  Move slash from pseudo element to actual span and add aria-hidden attribute to prevent screen readers from announcing it.
1. Use button with disabled attribute for active number (and give a label that screen readers can use)
=> [SDPA-1604] Adds better screen reader support for pagination.

packages/Atoms/Icon/TextIcon.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2420
1.  Fix empty a href tags causing sorry! page
=> [SDPA-2420] Fix empty a href tags causing sorry! page

packages/Molecules/Form/formPikaday.vue
1.  Make async import of pikaday check for default module
=> [SDPA-2424] Fix pikaday import

package-lock.json, packages/Molecules/Map/package.json
=> fix package.lock

packages/Atoms/Link/Link.vue, packages/Molecules/Card/CardContent.vue, packages/Molecules/Card/CardNavigationFeatured.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** None
1.  Fix for link inner - to display as inline.
=> Fix for link inner - to display as inline.

packages/Organisms/CampaignPrimary/index.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1585
1. Change image prop to Object
1. Add alt text to img
1. Add title to Svg image if its not in a link
1. Remove deprecated :xlink:href - https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
=> [SDPA-1585] Add alt text to campaign primary image

packages/Molecules/ShareThis/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2467
1.  Fix hover on social links.
=> [SDPA-2467] Fix hover on social links.

packages/Atoms/Link/Link.vue, packages/Molecules/Card/CardEmergencyContact.vue, test/__snapshots__/storyshots.test.js.snap
1.  Use span instead of div for innerwrap on rpl-link to fix invalid markup
=> Use span instead of div for innerwrap

.lagoon.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-336
1.  JIRA credentials in .lagoon.yml are now being stored as Lagoon variables.
=> [SDPSUP-336] : Re-add JIRA integration

.lagoon.yml, README.md
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2481
1.
=> [SDPA-2481] JIRA Integration test

package-lock.json, package.json, packages/Atoms/Global/mixins/uniqueid.js, packages/Organisms/Accordion/.npmignore, packages/Organisms/Accordion/Accordion.vue, packages/Organisms/Accordion/LICENSE, packages/Organisms/Accordion/README.md, packages/Organisms/Accordion/index.js, packages/Organisms/Accordion/package.json, packages/Organisms/Accordion/stories.js, packages/Organisms/Markup/README.md, src/storybook-components/PageAccordion.vue, src/storybook-components/_data/demoData.js, src/storybook-components/stories.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1606
1.  Adding Accordion to Ripple.
2. Add uniqueid mixin, and accordion expanded tag.
=> [SDPA-1606] Adding Accordion to Ripple.

package-lock.json, packages/Atoms/Global/scss/settings/_layout.scss
**Issue:** #356 
1.  Allowed _layout.scss to be themed
=> #356 Allow layout.scss to be themed

packages/Atoms/Global/index.js, packages/Atoms/Link/Link.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2519
1.  Add specific print url to links.
_Screenshot is of a nuxt when these changes are paired with nuxt changes._
_Ripple and nuxt changes side-by-side. Ripple left, Nuxt right._
=> [SDPA-2519] Add specific print url to links.

packages/Atoms/Global/scss/settings/_layout.scss, packages/Molecules/Layout/PageLayout.vue, packages/Molecules/Layout/stories.js, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2547
Github issues:
https://github.com/dpc-sdp/ripple/issues/356
https://github.com/dpc-sdp/ripple/issues/359
1.  Allowed _layout.scss to be themed
2. Added a columns prop to PageLayout to allow configuration
=> [SDPA-2547] issues from Today Agency

packages/Atoms/Global/scss/settings/_font.scss, packages/Atoms/Global/scss/tools/_typography.scss, packages/Atoms/Global/stories.js, src/storybook-components/Fonts.vue, src/storybook-components/Typography.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1097
* Added new variables to define spacing in line-height.
* Updated Typography story to allow custom text (test with different text).
* Added new story to test fonts with more options (size / line-height / weight / background).
=> [SDPA-1097] Define line heights for each font-size with a background.

.lagoon.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-344
1.  Added routes for  master environment  to .lagoon.yml
2. Added monitoring URL for production/master environment to .lagoon.yml
=> [SDPSUP-344] Added routes and monitoring URLs to .lagoon.yml.

packages/Organisms/Publication/PublicationDownloadPrint.vue
1.  Moved window.print into mounted hook and check if window is defined to avoid window is undefined error in SSR. Note : The component should still be rendered server side as there isn't really any other functionality which requires browser apis.
=> Check for window before calling window.print for SSR

package-lock.json
**JIRA issue:** No JIRA Issue.
1.  Version bump for highlight.js - fixes issue in https://github.com/highlightjs/highlight.js/issues/2043
=> Highlightjs version bump. Fixes firefox / safari error.

packages/Organisms/Publication/PublicationDownloadPrint.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2618
1.  Only show border on print if list items exist before.
=> [SDPA-2618] Only show border on print if list items exist before.

packages/Organisms/Publication/PublicationAuthorInformation.vue, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2613
1.  Change publication info date format to month and year.
=> [SDPA-2613] Change publication info date format to month and year.

packages/Molecules/AnchorLinks/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2625
1.  Remove border on right in safari
=> [SDPA-2625] Fix border gradient in safari.

packages/Atoms/Global/mixins/deprecate.js, packages/Molecules/Form/__tests__/fieldRplSelect.test.js, packages/Molecules/Form/fields/fieldRplchecklist.vue, packages/Molecules/Form/fields/fieldRplselect.vue, src/storybook-components/_data/demoData.js, test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2643
1.  Convert ripple select option id to valid css selector sting.
2. Added deprecated warning for ripple checklist.
=> [SDPA-2643] Fixed invalid css selector error

packages/Molecules/Form/fields/fieldRplselect.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2649
1.  Reset value to array after clear
=> [SDPA-2649] Fix select after clear form.

packages/Organisms/Publication/PublicationImage.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2675
1.  Adds default values for publication image labels.
=> [SDPA-2675] Adds default values for publication image labels.

.lagoon.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-441
1.  Set correct tls-acme setting in .lagoon.yml (`tls-acme: 'false'`)
=> [SDPSUP-441] Set correct tls-acme setting.

README.md
=> Added readme for beta

README.md, examples/vic-gov-au/package.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1482
1.  Adding support for windows cmd on example.
https://drive.google.com/file/d/1LEAn3iidO3t0NyfFbG_bURG8CaQ19SRE/view?usp=sharing
=> [SDPA-1482] Adding support for windows cmd on example.

examples/vic-gov-au/components/MyButton.vue, examples/vic-gov-au/pages/my-page.vue, packages/ripple-nuxt-tide/lib/components/AppForm.vue, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2798
1.  Added VicPol form redirect into core.
=> Added vicpol form redirect into core

packages/ripple-nuxt-ui/lib/module.js
=> Fix icons not rendering due to wrong path in ripple-nuxt-ui

packages/components/Molecules/EmbeddedVideo/index.vue, packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2498
1.  Transcript to use HTML.
=> [SDPA-2498] Transcript to use HTML.

packages/ripple-nuxt-tide/lib/components/AppForm.vue, packages/ripple-nuxt-tide/modules/webform/conditional-logic.js, packages/ripple-nuxt-tide/test/unit/webform.test.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2833
* Re-factored conditional logic code to improve readability.
* Added support for AND / OR / XOR operators.
* Added support for filled, checked, unchecked, value, !value, pattern, !pattern, less, greater triggers.
* Added conditional logic unit tests.
No screens.
**Note**: This contains a breaking change.
=> [SDPA-2833] Update webform conditional.

packages/components/Molecules/DescriptionList/DescriptionList.vue, packages/ripple-nuxt-tide/modules/publication/pages/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2651
* Publication: Prevent printing rows when row is empty.
* Remove default padding from description lists.
=> [SDPA-2651] Improve publication body and sidebar top alignment.

examples/vic-gov-au/nuxt.config.js, packages/ripple-nuxt-tide/modules/search/lib/search/module.js
1.  Fix search url not having hash
1.  Cast site id to string
=> Fix search not working in example app

packages/ripple-test-tools/index.js, packages/ripple-test-tools/page-models.js, packages/ripple-test-tools/tide-admin.js, packages/ripple-test-tools/util.js, test/e2e/fixtures/Pages/Event/event.json, test/e2e/integration/Events/Events.feature, test/e2e/integration/Events/Events/hooks.js, test/e2e/integration/Events/Events/step_definition.js, test/e2e/integration/common/index.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2747
* Added e2e test for event page.
* Added addWysiwygMediaEmbed() for adding a media (e.g. image) to a wysiwyg.
=> [SDPA-2747] Event page e2e test

packages/components/Molecules/Map/lib/ol.js
=> Added ol css back

packages/ripple-nuxt-tide/lib/core/basic-auth.js, packages/ripple-nuxt-tide/lib/module.js
=> fix addServerMiddleware middleware

packages/components/Organisms/CampaignSecondary/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2934
* Fix short campaign secondary text causing button wrapping.
=> [SDPA-2934] Fix short campaign secondary text causing button wrapping.

test/e2e/integration/LandingPage/DemoLandingPage.feature
1.  Don't run tests that aren't supported by the demo landing page.
=> Don't run tests that aren't supported by the demo landing page.

examples/vic-gov-au/assets/_custom.scss, examples/vic-gov-au/components/examples/Message.vue, examples/vic-gov-au/nuxt.config.js, packages/ripple-nuxt-tide/lib/layouts/default.vue, packages/ripple-nuxt-tide/lib/layouts/minimal.vue, test/e2e/integration/CustomCss/CustomCss.feature, test/e2e/integration/CustomCss/CustomCss/step_definition.js, test/e2e/integration/CustomMiddleware/CustomMiddleware.feature, test/e2e/integration/CustomMiddleware/CustomMiddleware/step_definition.js
1.  Removed redundant custom css in layout
2. Added example for how to use custom css
3. Added tests
=> Added custom css in example

packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/layouts/default.vue, packages/ripple-nuxt-tide/lib/templates/plugin.js, packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js, packages/ripple-nuxt-tide/modules/authenticated-content/plugin.js, packages/ripple-nuxt-tide/test/unit/authenticate.test.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2974
1.  Auth logic to store. Server always gets token from cookies.
=> [SDPA-2974] Server auth token

packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-668
1.  Fixes issue with client side navigation when token is set to null value.
=> [SDPSUP-668] Ignore null cookie for auth content.

packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js
=> Merge back hotfix

packages/components/Atoms/Global/mixins/parentlinks.js, packages/components/Molecules/Sitemap/SitemapMenu.vue, packages/components/Organisms/SiteFooter/FooterNavigation.vue, packages/components/Organisms/SiteFooter/LinksAndCopyright.vue, packages/components/Organisms/SiteHeader/menu.vue, packages/components/Organisms/SiteSectionNavigation/menu.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2723
1.  Add link target="" support to components that display menus.
No screens.
=> [SDPA-2723] Add link target="" support to components that display menus.

packages/components/Molecules/List/index.vue
1.  Rpl-List: fix warning caused by incorrect :key in v-for
=> [SDPA-3061] fix vue warning on Rpl-List

packages/components/Molecules/Layout/PageLayout.vue, packages/components/Organisms/HeroBanner/HeroBanner.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2594
* Use grid and layout variables to calculate background position.
* Move scss variables into an array / map to reduce repetition.
The background position uses these rules as guidelines:
* The graphic should at least reach the right edge of the window.
* The graphic should sit 100px underneath the orange box (unless doing so breaks rule 1).
* The top of the graphic edge should touch the bottom right of the orange box (Assuming the orange box sits 68px from the bottom of the hero banner).
=> [SDPA-2594] Hero Banner background position.

packages/components/Organisms/Grants/GrantsOverview.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1408
1.  Provide more precise scaling options for icons.
=> [SDPA-1408] Provide more precise scaling options for icons.

packages/components/Atoms/Global/README.md, packages/components/Atoms/Global/scss/settings/_font.scss, packages/components/Atoms/Global/scss/settings/_variables.scss, packages/components/Atoms/Global/scss/tools/_typography.scss, packages/components/Atoms/Global/stories.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-910
* Add padding to Display Heading typography.
* Update typography function to optionally include base rules (rules that are only needed once for all breakpoints).
=> [SDPA-910] Add padding to Display Heading typography.

packages/components/Organisms/HeroBanner/HeroBanner.vue, packages/ripple-nuxt-tide/lib/pages/Tide.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2985
1.  Fix acknowledgment field name and hero banner border.
=> [SDPA-2985] Fix acknowledgment field name and hero banner border.

packages/components/Organisms/HeroBanner/HeroBanner.vue, packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapPreventionFamilyViolence.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3072
1.  Updated Her Banner text / description font size and margins.
2. Fix: Move unscoped heading 1 rule into tide-map selector.
=> [SDPA-3072] Hero banner fonts

packages/ripple-nuxt-tide/lib/module.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3074
1.  Added Winston modules in babel transpile to fix IE 11 syntax error
=> [SDPA-3074] Added Winston modules in babel transpile

packages/components/Atoms/Link/Link.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2723
1.  Fix: A rpl-link 'target' prop change will update target attr
=> [SDPA-2723] Fix: A rpl-link 'target' prop change will update target attr

packages/ripple-nuxt-tide/lib/components/AppTopicTags.vue, packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue, packages/ripple-nuxt-tide/modules/page/pages/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-369
* Move Topic and Tags into separate component.
* Update landing page and page content type to use component.
**NOTE** This affects the implementation on SDPA-372. As such this has been based off that branch and **should be merged when SDPA-372** is in develop.
=> [SDPA-369] Page topic tags

examples/vic-gov-au/store/index.js, packages/ripple-nuxt-tide/lib/core/logger.js, packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/core/tide-helper.js, packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/lib/server-middleware/request-id.js, packages/ripple-nuxt-tide/lib/server-middleware/request-log.js, packages/ripple-nuxt-tide/lib/templates/plugin.js, packages/ripple-nuxt-tide/lib/templates/request-id.js, packages/ripple-nuxt-tide/modules/publication/tide.middleware.js, packages/ripple-nuxt-tide/modules/site/plugin.js, packages/ripple-nuxt-tide/package.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3045
1.  Added a unique id for each route request
2. Added the request id in BE request header
3. Added the request id in log
4. Rename "results" to "pageData" in middleware to make it meaningful.
=> [SDPA-3045] Added request id in all route requests

packages/components/Molecules/Layout/PageLayout.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1888
1.  Fix: Safari hero banner graphic glitch with a slight decimal percentage.
=> [SDPA-1888] Fix: Safari hero banner graphic glitch.

packages/components/Molecules/Card/CardHonourRoll.vue, packages/components/Molecules/Card/CardProfile.vue, packages/components/Molecules/Card/README.md, packages/components/Molecules/Card/index.js, packages/components/Molecules/Card/stories.js, packages/components/Molecules/Search/SearchResults.vue, packages/ripple-nuxt-tide/modules/profile/pages/search.vue, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3034
* Deprecated CardHonourRoll
* Added CardProfile
* Card Profile has no category, and inducted prefix
* Profiles search page to use CardProfile
=> [SDPA-3034] Card Profile

packages/components/Atoms/MetaTag/index.vue, packages/components/Organisms/Accordion/Accordion.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2965
* Add slight padding to accordions.
* Update accordion text / icon colours for print.
* Accordion icon to always appear downwards on print.
* Fix MetaTag border colour for print.
=> [SDPA-2965] Accordion print styling.

packages/components/Organisms/SiteSectionNavigation/index.vue
1.  Add !default to $rpl-section-menu-background-color to make BG colour overridable.
=> Add !default to $rpl-section-menu-background-color to make overridable.

examples/basic-examples/assets/_custom.scss, examples/basic-examples/store/index.js, packages/ripple-nuxt-tide/README.md
=> [SDPA-2910] Fixed a broken url in docs with other typo fix

packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3043
1.  Add field limit of 1000 to Content Rating 'Please add your comments' field.
=> [SDPA-3043] Add field limit to Content Rating.

packages/components/Atoms/Global/scss/tools/_breakpoints.scss, packages/components/Molecules/Card/README.md, packages/components/Molecules/Layout/README.md, packages/components/Molecules/Layout/package.json, packages/components/Organisms/CampaignPrimary/CampaignPrimaryImage.vue, packages/components/Organisms/CampaignPrimary/README.md, packages/components/Organisms/CampaignPrimary/index.vue, packages/components/Organisms/CampaignPrimary/package.json, packages/components/Organisms/CampaignPrimary/stories.js, packages/components/Organisms/Grants/README.md, packages/components/Organisms/SiteFooter/README.md, packages/ripple-nuxt-tide/lib/config/tide.config.js, packages/ripple-nuxt-tide/lib/core/mapping-filters.js, packages/ripple-nuxt-tide/lib/core/middleware.js, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3048
* Added a mixin to handle setting bulk breakpoints for a single rule.
* Added caption and styles.
* Update snapshot / docs
* Remove icon dependency. Not used.
* Move SVG into a separate component for use in else statement.
* Fixed hasAlt function - now always returns a boolean.
* Image and Caption are now part of <figure>, visible caption is aria hidden.
* Nuxt mapping of primary campaign caption.
NOTE: Primary campaign went through a bit of a restructure (moved the SVG into it's own component) in order to support figcaption, consistent with how we deal with our other captioned images using `<rpl-figure>`.
=> [SDPA-3048] Primary campaign caption

packages/components/Organisms/SiteFooter/SiteFooter.vue, packages/components/Organisms/SiteFooter/stories.js, packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/layouts/default.vue, packages/ripple-nuxt-tide/lib/templates/plugin.js, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3046
1.  Add hero image caption.
2. Update nuxt to pass the value through store.
=> [SDPA-3046] Hero banner caption

packages/ripple-nuxt-tide/modules/event/formdata.js, packages/ripple-nuxt-tide/modules/event/pages/search.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3122
1.  Set date filter to end of day to include results for that day.
=> [SDPA-3122] Date filter fix.

packages/components/Atoms/Global/utils/helpers.js, packages/components/Molecules/Card/CardKeydates.vue, packages/components/Molecules/Card/__test__/cardKeydates.test.js, packages/ripple-nuxt-tide/lib/core/tide-helper.js, packages/ripple-nuxt-tide/modules/publication/pages/index.vue, packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
- https://digital-engagement.atlassian.net/browse/SDPA-3163
- Truncate title and description if there are multiple Keydates.
- Truncate title to 40 characters if the description is more than 80 characters.
- Else truncate the title to 80 characters.
- Truncate description to 120  characters if the length is more than 120.
=> [SDPA-3163] CardKeydates truncate text to fit in the card

packages/ripple-nuxt-tide/lib/core/middleware.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3250
1.
=> [SDPA-3250] Fix broken head if sitesection doesn't exist

.circleci/config.yml, packages/ripple-nuxt-tide/lib/core/tide.js
1.  Added a request in CI to awake dev BE before e2e test
2. Increased timeout for CI tests
=> Added different timeout for CI test

packages/components/Molecules/Map/Map.vue, packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapPreventionFamilyViolence.vue, packages/ripple-nuxt-tide/modules/data-driven-component/components/TideVicFreeWifiMap/TideVicFreeWifiMap.vue, packages/ripple-nuxt-tide/modules/data-driven-component/lib/fetch-external-data.js, src/storybook-components/MapVicFreeWifi.vue
1.  Updated the domain for the MyVIC endpoints in the MyVIC Maps.
=> Updated the domain for the MyVIC endpoints in the MyVIC Maps.

packages/create-ripple-app/cli.js, packages/create-ripple-app/generators/updates/18.0.0/saofile.js, packages/create-ripple-app/package.json, packages/create-ripple-app/template/_package.json, packages/ripple-test-tools/package.json, yarn.lock
=> Remove explicit file paths and fix bin command path

packages/components/Molecules/EmbeddedVideo/index.vue, packages/components/Molecules/EmbeddedVideo/stories.js, packages/components/Organisms/Markup/examplePlugins.js, packages/ripple-nuxt-tide/lib/config/markup-plugins.js, packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js, packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3389
1.  In `pluginEmbeddedMediaVideo`, use "back quote" to replace "single quote" in object type prop template.
2. Removed unneeded `lang` attr from video iframe.
3. Updated `components/Organisms/Markup/examplePlugins.js` to match the latest.
4. Added all missing tests for markup plugins, to make sure 100% coverage.
=> [SDPA-3389] embedded video error

packages/create-ripple-app/generators/new/saofile.js, packages/create-ripple-app/template/_.env, packages/create-ripple-app/template/nuxt/.gitignore
=> Add dotenv file for new projects using create ripple app

packages/create-ripple-app/generators/updates/18.0.0/saofile.js
=> Fixed create app update script typo

packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/lib/templates/axios.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPUP-1097
1.  Added missing `res` context in axios plugins, fixed error status code set.
2. Added extra error code setting in page load.
=> [SDPUP-1097] homepage error code

examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature, packages/components/Atoms/Global/scss/tools/_grid.scss, packages/components/Molecules/AnchorLinks/index.vue, packages/components/Molecules/Card/CardBox.vue, packages/components/Molecules/Card/CardContent.vue, packages/components/Molecules/Card/CardNavigationFeatured.vue, packages/components/Molecules/Card/no-ssr/CardCarousel.vue, packages/components/Molecules/Form/index.vue, packages/components/Molecules/Layout/PageLayout.vue, packages/components/Molecules/Map/Map.vue, packages/components/Organisms/CallToAction/index.vue, packages/components/Organisms/HeroBanner/HeroBanner.vue, packages/components/Organisms/ImageGallery/no-ssr/ImageGallery.vue, packages/components/Organisms/News/NewsListing.vue, packages/components/Organisms/Publication/PublicationImage.vue, packages/create-ripple-app/template/_example/tide/modules/event/pages/index.vue, packages/ripple-nuxt-tide/lib/components/AppContentRating.vue, packages/ripple-nuxt-tide/modules/event/pages/index.vue, packages/ripple-nuxt-tide/modules/grant/pages/index.vue, packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue, packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue, packages/ripple-nuxt-tide/modules/news/pages/index.vue, packages/ripple-nuxt-tide/modules/page/pages/index.vue, packages/ripple-nuxt-tide/modules/profile/pages/index.vue, packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue, packages/ripple-nuxt-tide/modules/publication/pages/index.vue, packages/ripple-test-tools/step_definitions/common/modules/events.js, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** 
https://digital-engagement.atlassian.net/browse/SDPA-3307
https://digital-engagement.atlassian.net/browse/SDPA-3341
https://digital-engagement.atlassian.net/browse/SDPA-3315
https://digital-engagement.atlassian.net/browse/SDPA-3435
- Removed print hidden style for most of components
- Updated heading style for publication print all
- Fixed map print issue
- Fixed card carousel print issue
- Fixed page title print style
- Added class for content type template container
- Fixed missing content in publication print
=> [SDPA-3307][SDPA-3341][SDPA-3415] [SDPA-3435] print publication issue

packages/ripple-nuxt-tide/modules/webform/conditional-logic.js
1.  Added the webforms conditional logic: 
```
∙ visible
∙ invisible
∙ enabled
∙ disabled
```
=> Update the webforms conditional logic

packages/components/Organisms/Markup/Markup.vue, packages/components/Organisms/Markup/markup-transpiler.js, packages/ripple-nuxt-tide/lib/config/markup-plugins.js, packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap, packages/ripple-nuxt-tide/test/unit/markup-transpiler.test.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3449
1.  Fixed ie11 issue by using vue data to replace string in template
=> [SDPA-3449] IE11 video transcript

packages/components/Atoms/Global/index.js, packages/components/Organisms/SiteFooter/SiteFooter.vue, packages/ripple-nuxt-ui/lib/templates/plugin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3469
1. Added footer-logo in rplOptions so that footer-logo can be turned on and off from nuxt config.
=> [SDPA-3469] Added Footer logo onoff option in nuxt config

packages/create-ripple-app/template/_package.json, packages/create-ripple-app/template/nuxt/nuxt.config.js, packages/create-ripple-app/template/nuxt/robots.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3518
1.  Added Nuxt robots in create app template, to reduce the work for each site creation.
=> [SDPA-3518] Added nuxt robots to new project

packages/components/Molecules/Form/Select.vue, packages/components/Molecules/Form/fields/fieldRplselect.vue, src/test/__snapshots__/storyshots.test.js.snap
1.  Fixes placeholder not being configurable for fieldRplSelect
1. Fixes error on click when there are no options passed to rpl-select
=> Fix placeholder not configurable for fieldRplSelect

packages/components/Molecules/Form/index.vue, packages/components/Molecules/Form/stories.js, src/test/__snapshots__/storyshots.test.js.snap
1.  Adds search icon for input field by adding styleClass
=> [SDPL-169] Adds search icon for input field

packages/components/Molecules/Form/fields/fieldRplclearform.vue, packages/components/Molecules/Form/fields/fieldRploptionbutton.vue, packages/components/Molecules/ListGroup/index.js, src/test/__snapshots__/storyshots.test.js.snap
1. Add border-radius to first and last item in option group at Desktop BP
1.  Fix clear button text color
1. Fix export for list-group item
=> [SDPL-169] Adds border radius to option group

.circleci/config.yml, packages/components/Organisms/Markup/stories.js, packages/create-ripple-app/__tests__/new.test.js, src/test/__snapshots__/storyshots.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1208
1. Updated to BE link for develop to exclude 'www' at the front.
=> [SDPSUP-1208] Updated the BE link to remove www from develop.

examples/vic-gov-au/nuxt.config.js, packages/components/Organisms/Publication/PublicationAuthorInformation.vue, packages/components/Organisms/Publication/stories.js, packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue, packages/ripple-nuxt-tide/modules/publication/pages/index.vue, packages/ripple-nuxt-tide/modules/publication/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3491
1.  Added the type array for author prop.
2. changed to get the correct array value of author names from the field.
3. Did the same change for the print page.
4. Changed the prop type in the storybook to reflect it. 
Publication Page - 
Print all page -
=> [SDPA-3491] publication author field bug fix.

examples/vic-gov-au/nuxt.config.js
=> [remove-test-link] Updated nuxt config in vic gov example.

packages/components/Molecules/Form/index.vue, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1212
1.  Added custom form validation methods to check number of words in textArea and textField form elements if configured under the "Form Validation" tab in Drupal.
2.  Counter_maximum and counter_minimum values override maxlength and minlength if both are set.
3. Move to using VFG validation instead of browser validation for all free text fields (textArea, textField, tel, url, email)
=> [SDPSUP-1212] : Add word count form validation

examples/vic-gov-au/test/e2e/fixtures/media/embedded-video.yml, examples/vic-gov-au/test/e2e/integration/core-modules/media/media.feature, packages/ripple-nuxt-tide/lib/config/markup-plugins.js, packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js, packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap, packages/ripple-test-tools/step_definitions/common/index.js, packages/ripple-test-tools/step_definitions/common/modules/media.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3545
1.
=> [SDPA-3545] video link

packages/ripple-nuxt-tide/package.json, yarn.lock
1.  Add dependency security fix for Nuxt. This should be removed after Nuxt released https://github.com/nuxt/nuxt.js/pull/6769.
=> chore(deps): update dependency serialize-javascript to ^2.1.1

examples/basic-examples/package.json, examples/vic-gov-au/package.json, packages/create-ripple-app/__tests__/__mocks__/v18/package.json, packages/create-ripple-app/generators/updates/18.0.0/saofile.js, packages/create-ripple-app/template/_package.json, packages/ripple-nuxt-tide/package.json, packages/ripple-nuxt-ui/package.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3563
1.  Updated Nuxt to v2.10.2
2. Updated yarn lock to cleanup some deps version
=> [SDPA-3563] updated deps

packages/components/Molecules/ListGroup/index.js, packages/ripple-nuxt-tide/package.json
=> Add ripple-list-group dependency in nuxt-tide

examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature, packages/components/Organisms/Publication/PublicationAuthorInformation.vue, packages/components/Organisms/Publication/package.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3652
1.  Added required dependency in publication component package
=> [SDPA-3652] publication author doesn't show

examples/vic-gov-au/test/e2e/fixtures/media/embedded-video-no-transcript.yml, examples/vic-gov-au/test/e2e/fixtures/media/embedded-video.yml, examples/vic-gov-au/test/e2e/integration/core-modules/media/media.feature, packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue, packages/ripple-test-tools/commands.js, packages/ripple-test-tools/step_definitions/common/components.js, packages/ripple-test-tools/step_definitions/common/modules/media.js, packages/ripple-test-tools/step_definitions/common/navigation.js, packages/ripple-test-tools/tide-admin/index.js
=> [SDPA-3421] Fix embedded video issues with no transcript and add tests

examples/vic-gov-au/nuxt.config.js, examples/vic-gov-au/test/e2e/integration/smoke/Headers.feature, packages/ripple-nuxt-tide/README.md, packages/ripple-nuxt-tide/lib/config/constants.js, packages/ripple-nuxt-tide/lib/config/defaults.js, packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/lib/server-middleware/headers.js, packages/ripple-nuxt-tide/lib/templates/axios.js, packages/ripple-nuxt-tide/lib/templates/cache-purge.js, packages/ripple-test-tools/step_definitions/common/utils.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3649
1.
=> [SDPA-3649] Added headers to help ops

packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3341
1.  Added contact us component for parent publication in print-all.
=> [SDPA-3341] Publication print "contact us" component for parent.

packages/ripple-nuxt-tide/modules/search/lib/search/module.js, packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/querybuilder.js
1.  to make checkbox search filter working
=> Search checkbox filter

packages/ripple-test-tools/package.json, packages/ripple-test-tools/scripts/cucumberconvertor.js
=> [SDPA-3576] Remove glob-fs dependency and use glob instead

examples/basic-examples/nuxt.config.js, examples/vic-gov-au/nuxt.config.js, packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/layouts/default.vue, packages/ripple-nuxt-tide/lib/pages/Sitemap.vue, packages/ripple-nuxt-tide/lib/pages/Tide.vue, packages/ripple-nuxt-tide/lib/templates/plugin.js, packages/ripple-nuxt-tide/modules/authenticated-content/pages/Login.vue, packages/ripple-nuxt-tide/modules/authenticated-content/pages/Reset.vue, packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue, packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js, packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
**JIRA issue:** https://salsadigital.atlassian.net/browse/WSM-188
- Implement a store to set head.
- Include "| site name" to title.
- Updated the following pages to use the store value:
- Search pages (including /search, /whatson, /grants, /profiles)
- Authenticated pages (login / reset)
- Publication PrintAll
- Sitemap
- Tide pages (landing pages, 400 / 500 pages, and generally all other pages)
=> Accessibility: Page Head

examples/vue-example-app/package.json, examples/vue-example-app/src/variables.scss, packages/components/Atoms/Global/scss/settings/_color.scss, packages/components/Atoms/Global/scss/settings/_colorcore.scss, packages/components/Atoms/Global/scss/settings/_functions.scss
Previous PR https://github.com/dpc-sdp/ripple/pull/655 caused an issue in custom site scss build. 
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
@return map-merge($rpl-colors-core, $rpl-colors);
^
Undefined variable: "$rpl-colors-core".
in /root/app/packages/components/Atoms/Global/scss/settings/_functions.scss (line 70, column 21)
Added new core color var before function load to make current site theme continually working.
=> Fixed Undefined variable: "$rpl-colors-core" error

examples/vic-gov-au/test/e2e/integration/modules/publication/publication.feature, packages/ripple-nuxt-tide/modules/publication/tide.middleware.js, packages/ripple-test-tools/step_definitions/components/index.js, packages/ripple-test-tools/step_definitions/index.js, packages/ripple-test-tools/step_definitions/modules/publications.js
1.  Add nested object checking in publication head meta when head not present
=> [SDPA-4204] Fix publication header bug

packages/components/Molecules/Form/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4200
1.  Fixed `rplWordCount` validation error when value is undefined(User didn't enter any input), by adding a value check.
=> [SDPA-4200] form validation error

examples/vic-gov-au/test/e2e/integration/smoke/Homepage.feature
1.  Accessibility audit result on dynamic homepage is inconsistent, will add back when we have reference site static content setup.
=> test: ignored accessibility audit on dynamic homepage

packages/ripple-nuxt-tide/lib/module.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4224
1.  Remove `section-io-id` from proxy request to backend
=> [SDPA-4224] Remove section-io-id from proxied req

packages/components/Molecules/Card/__snapshots__/stories.storyshot, packages/components/Molecules/Search/__snapshots__/searchlayout.stories.storyshot, packages/components/Molecules/WhatsNext/__snapshots__/stories.storyshot, packages/components/Organisms/CallToAction/__snapshots__/stories.storyshot, packages/components/Organisms/CallToAction/index.vue, packages/components/Organisms/CallToAction/stories.js, packages/components/Organisms/Grants/__snapshots__/stories.storyshot, packages/components/Organisms/HeroBanner/__snapshots__/stories.storyshot, packages/components/Organisms/ImageGallery/__snapshots__/stories.storyshot, packages/components/Organisms/Markup/__snapshots__/stories.storyshot, packages/components/Organisms/News/__snapshots__/stories.storyshot, packages/components/Organisms/Profile/__snapshots__/stories.storyshot, src/.storybook/config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4325
1.  Changed call to action summary to html format
2. Fixed story snapshot for HTML format support
=> [SDPA-4325] Changed call to action summary to html format

packages/ripple-nuxt-tide/modules/media/tide.middleware.js
1.  Fixed the breadcrumbs in media page
=> Fixed breadcrumbs on media

packages/components/Molecules/Contact/index.vue
1.  Related to the patch on this PR - https://github.com/dpc-sdp/firerescue-vic-gov-au/pull/5
=> [SW-8-patch-fix] Added patch fix.

packages/components/Molecules/Layout/PageLayout.vue
1.  Adds variable for grey page BG
=> Make bg grey colour customisable

packages/ripple-nuxt-tide/lib/core/tide.js
1.  Added an error handling for unknown entity bundle. If the Tide route API return an entity bundle which is not found in include configs, will return an error.
=> Added error handling for unknow content type

examples/basic-examples/nuxt.config.js, examples/vic-gov-au/nuxt.config.js, packages/create-ripple-app/generators/updates/1.23.1/saofile.js, packages/create-ripple-app/generators/updates/1.26.0/saofile.js, packages/create-ripple-app/template/nuxt/nuxt.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-258
1.  reverted extractCSS work due to Nuxt extrctCSS preload bug.
2. revert extractCSS in next update for SDP sites.
=> [SW-258] revert extract css work

packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/modules/webform/mixins/index.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4515
1.  Fixed login error. The login POST url contains parameter already which made an invalid url.
=> [SDPA-4515] Fixed login error

packages/ripple-nuxt-tide/package.json
=> Fix missing ripple-responsive-img package

packages/ripple-nuxt-tide/lib/core/tide-helper.js, packages/ripple-nuxt-tide/lib/middleware/page-head.js
1.  Adds html lang attribute based on Drupal `Content Language` meta. It seems langcode is not populated in JSON api from this value
=> [SDPSUP-2024] Add html lang attr from meta tag

packages/components/Organisms/CallToAction/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4608
1.  Add support for rendering CTA component without a Featured Image.
=> [SDPA-4608] : Add imageless support for CTA component

packages/components/Organisms/CallToAction/index.vue
1.  Adds height auto for CTA image so it doesn't take up the original img height.
**Existing**
**With fix**
=> Fix CTA image positioning for large images

packages/components/Atoms/Global/scss/settings/_colorcore.scss, packages/components/Atoms/Global/scss/settings/_functions.scss, packages/components/Organisms/Markup/Markup.vue
=> Update callout background colour

packages/ripple-nuxt-tide/lib/core/middleware.js, packages/ripple-nuxt-tide/lib/core/utils/site-section.js, packages/ripple-nuxt-tide/lib/layouts/default.vue, packages/ripple-nuxt-tide/lib/middleware/sidebar.js, packages/ripple-nuxt-tide/lib/mixins/page.js, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/lib/templates/page.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4316
1.  Updated quickexit logic to handle site section level
2. Added a global page mixin for the ability to set ripple option on every page.
=> [SDPA-4316] quick exit by section

examples/vic-gov-au/test/e2e/integration/smoke/elasticsearch.feature
=> [skip-search-smoke-test] Updated test to skip search smoke test.

packages/ripple-nuxt-tide/modules/authenticated-content/components/TideLogin.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4694
1.  Updated error message for authenticated content register form
=> [SDPA-4694] Updated error message for register

packages/ripple-nuxt-tide/lib/core/tide-helper.js, packages/ripple-nuxt-ui/lib/templates/plugin.js, packages/ripple-nuxt-ui/package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4737
1.  Moved helper function `queryString` from ripple-nuxt-tide to ripple-nuxt-ui, so we won't have a dependency loop.
The correct dependency graph should be:
```
@dpc-sdp/ripple-nuxt-tide
└──@dpc-sdp/ripple-nuxt-ui
```
However current it is:
```
@dpc-sdp/ripple-nuxt-tide
└──@dpc-sdp/ripple-nuxt-ui
└──@dpc-sdp/ripple-nuxt-tide
```
=> [SDPA-4737] fix dependency loop

packages/components/Organisms/Markup/Markup.vue
1.  Added word wrap to break long non-breaking words which gets truncated in mobile.
=> [SDPA-4741] Break long words such as url and emails into next line

packages/ripple-nuxt-tide/lib/config/tide.config.js, packages/ripple-nuxt-tide/lib/mixins/data-layer.js, packages/ripple-nuxt-tide/lib/pages/Tide.vue, packages/ripple-nuxt-tide/modules/gtm/templates/plugin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4774
1.  Created mixin to add data to gtm dataLayer specifically for department field
=> [SDPA-4774] Create mixins to add department to gtm datalayer

packages/components/Atoms/Link/TextLink.vue, packages/components/Molecules/Alert/__snapshots__/stories.storyshot, packages/components/Molecules/Form/Fieldset.vue, packages/components/Molecules/Form/index.vue, packages/components/Molecules/RelatedLinks/__snapshots__/stories.storyshot, packages/components/Molecules/ShareThis/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-552
1.  Add color variables for:
- $rpl-fieldset-legend-color
- $rpl-fieldset-legend-ruleset
- $rpl-form-title-color
- $rpl-form-label-color
- $rpl-form-hint-color
- $rpl-share-this-title-color
2. Add dark focus to links with dark theme.
=> Link / Form / Share colour variables and dark link focus

packages/ripple-nuxt-tide/modules/publication/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4765
1.  Added hero image field mapping for publication and publication page.
BE PR - https://github.com/dpc-sdp/tide_publication/pull/14
BE env - https://nginx-php-content-vic-pr-1005.lagoon.vicsdp.amazee.io/
Publication Page - 
Publication child page -
=> [SDPA-4766] Added hero image iin publication and publication page.

packages/components/Molecules/Search/SearchForm.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-595
Consistent styling of Search Form placeholder between Firefox & Chrome.
Adds 2 variables in to allow custom colors.
=> Search form input placeholder colour

packages/ripple-nuxt-tide/modules/publication/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4765
1.  Added hero image field mapping for publication and publication page.
This pr created again for the master so that we can do a release only with this change from the master branch.
=> [SDPA-4766] Added hero image field mapping for publication.

.circleci/config.yml
1.  Clear cache to try fix Circle build error
=> Clear ci cache

packages/create-ripple-app/generators/updates/1.31.0/saofile.js, packages/create-ripple-app/template/_package.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4647
1.  Added update script for next release so we can apply project level dependencies update to customer site .e.g nuxt
2. Updated same changes to new site template
=> [SDPA-4647] update script for updating deps in customer site

examples/basic-examples/package.json, examples/vic-gov-au/package.json, examples/vue-example-app/package.json, package.json, packages/create-ripple-app/generators/updates/1.31.0/saofile.js, packages/create-ripple-app/template/_package.json, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/package.json, packages/ripple-tide-search-api/package.json, yarn.lock
1.  Bump minor versions of dependency
- Nuxt - has bug fixes to trasnspile packages in nested node_modules (https://github.com/nuxt/nuxt.js/releases)
2. Bump core-js to version 3 to support up to ES2021
3. Add transpile for `async` and `is-stream` used in Winston
https://app-ripple-pr-852.lagoon.vicsdp.amazee.io/
=> Add transpile for is-stream and and async for IE11

packages/ripple-nuxt-tide/lib/module.js
=> Revert back winston-transport and add is-stream in transpile list

packages/ripple-nuxt-tide/lib/config/tide.config.js, packages/ripple-nuxt-tide/modules/content-vic/README.md, packages/ripple-nuxt-tide/modules/content-vic/tide.config.js
1.  Split content vic feature to content vic module. For semis, will need to enable this module in their nuxt config
=> Split content vic feature to content vic module

packages/components/Molecules/Card/CardNav.vue, packages/components/Molecules/Card/CardNavigation.vue, packages/components/Molecules/Card/CardNavigationV2.vue, packages/components/Molecules/Card/CardPromo.vue, packages/components/Molecules/Card/CardPromotion.vue, packages/components/Molecules/Card/__snapshots__/stories.storyshot, packages/components/Molecules/Card/__test__/CardPromo.test.js, packages/components/Molecules/Card/mixins/card.js, packages/components/Molecules/Card/scss/_card.scss, packages/components/Molecules/Card/stories.js, packages/ripple-nuxt-tide/lib/core/component-loader.js, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4714
1.  Added Tide config to map card promo component
2. Moved common css styling for both nav and promo components into cards.scss to easily manage
=> [SDPA-4714] card promo config

examples/vic-gov-au/nuxt.config.js, packages/components/Molecules/Card/CardNav.vue, packages/components/Molecules/Card/CardNavigation.vue, packages/components/Molecules/Card/CardPromo.vue, packages/components/Molecules/Card/CardPromotion.vue, packages/components/Molecules/Card/__snapshots__/stories.storyshot, packages/components/Molecules/Card/__test__/CardPromo.test.js, packages/components/Molecules/Card/index.js, packages/components/Molecules/Card/mixins/card.js, packages/components/Molecules/Card/scss/_card.scss, packages/components/Molecules/Card/stories.js, packages/ripple-nuxt-tide/lib/core/component-loader.js, packages/ripple-nuxt-tide/lib/core/mapping-filters.js, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4716
1.  Added configuration to map to navigation component props
=> [SDPA-4716] Add configuration for card navigation

renovate.json
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4906
1. Updated renovate config to add grouping for non major updates
none
=> [SDPA-4906] Group non major update

packages/components/Atoms/Icon/TextIcon.vue, packages/components/Atoms/Icon/__tests__/text-icon.test.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4891
1. Updated validation of getting first and last word
https://storybook-ripple-pr-869.lagoon.vicsdp.amazee.io/?path=/story/atoms-icon--text-icon
=> [SDPA-4891] Fix text link multiple spaces issue

packages/components/Organisms/Markup/package.json, packages/ripple-nuxt-tide/package.json, yarn.lock
1. Customer site auto updates cheerio to its latest version which causes `TypeError: can get _options of undefined` - this should be fixed when this changes is in their next release https://github.com/cheeriojs/cheerio/blob/main/lib/static.js#L121 (currently not in rc5)
=> Lock cheerio version to 1.0.0-rc.2

packages/components/Molecules/Card/CardPromo.vue, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
**JIRA issue:** 
https://digital-engagement.atlassian.net/browse/SDPA-4878
https://digital-engagement.atlassian.net/browse/SDPA-4877
1.  Set a max-width limit to card promo
2. Update cols layout
=> [SDPA-4878] Add max-width and update cols setting

packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/lib/templates/plugin.js, packages/ripple-nuxt-tide/modules/preview/module.js, packages/ripple-nuxt-tide/modules/preview/templates/plugin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDSUP-2507
1. Handling the several nuxt auth errors better
none, e2e test will be added in nightwatch
=> [sdpsup-2507] preview error

.circleci/config.yml, examples/basic-examples/package.json, examples/vic-gov-au/package.json, packages/create-ripple-app/__tests__/__mocks__/v18/package.json, packages/create-ripple-app/generators/updates/1.31.2/saofile.js, packages/create-ripple-app/generators/updates/1.32.0/saofile.js, packages/create-ripple-app/template/_package.json, packages/ripple-nuxt-tide/package.json, packages/ripple-nuxt-ui/package.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4937
1. 
TODO:
Update create-ripple-app package.json generator with SDP release version
=> [SDPA-4937] Upgrade nuxt 

packages/create-ripple-app/template/_example/tide/modules/event/tide.config.js, packages/ripple-nuxt-tide/modules/event/tide.config.js, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js, packages/ripple-nuxt-tide/modules/publication/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4975
1. Removed `field_paragraph_reference` from include param in API request
=> [SDPA-4975] Remove field_paragraph_reference as this has been deleted in BE

.circleci/config.yml, .eslintrc.js, CONTRIBUTING.md, packages/components/Organisms/Grants/Grants.stories.mdx, packages/components/Organisms/Markup/Markup.stories.mdx, src/.gitignore, src/package.json, yarn.lock
Snapshot testing has stop working due to a known issue in Storybook v6. We need an alternative UI testing to replace it.
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4993
1. Added chromatic visual testing.
storybook test job in CircleCI
=> [SDPA-4993] Add chromatic ui testing

renovate.json
1. Temporarily exclude cheerio in auto-update as it has breaking change
=> Renovate exclude cheerio from auto updating

packages/components/Molecules/Card/Card.stories.mdx, packages/components/Molecules/Card/CardNav.vue, packages/components/Molecules/Card/CardPromo.vue, packages/components/Organisms/Grants/Grants.stories.mdx, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5027
1. Removed column setting for navigation_card
2. Updated component width breakpoint settings
3. Added content max-width to card content
4. Updated storybook card date to use static for chromatic ui testing to pass
https://app.pr-910.ripple.sdp1.sdp.vic.gov.au/
https://storybook.pr-910.ripple.sdp1.sdp.vic.gov.au
=> [SDPA-5027] Remove column setting for navigation_card and update component breakpoint

examples/basic-examples/package.json, examples/vic-gov-au/package.json, packages/components/Organisms/Grants/Grants.stories.mdx, packages/create-ripple-app/__tests__/__mocks__/v18/package.json, packages/create-ripple-app/generators/updates/1.32.0/saofile.js, packages/create-ripple-app/template/_package.json, packages/ripple-nuxt-tide/package.json, packages/ripple-nuxt-ui/package.json, yarn.lock
1. Upgraded nuxt from 2.14 to 2.15.2
https://app.pr-912.ripple.sdp1.sdp.vic.gov.au
https://storybook.pr-912.ripple.sdp1.sdp.vic.gov.au
=> Update nuxt to 2.15.2

packages/components/Molecules/Card/CardNav.vue, packages/components/Molecules/Card/CardPromo.vue, packages/components/Molecules/Card/__test__/CardPromo.test.js, packages/components/Molecules/Card/mixins/card.js, packages/components/Molecules/EmbeddedVideo/EmbeddedVideo.stories.mdx, packages/components/Organisms/Markup/Markup.stories.mdx, packages/ripple-nuxt-tide/modules/landing-page/components/CardCollection.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-789
1. Updated card nav and card promo image props to accept string type
2. Added displayStyle and showMeta with default value in Card collection
=> [SW-789] card collection fixes

examples/basic-examples/tide/modules/example-content-type/tide.config.js
Docs are not clear about how to add custom Drupal content types when it contains multiple words.
1. Updated docs in example module
=> Updated docs for custom content type

examples/vic-gov-au/test/e2e/integration/smoke/DemoLandingPage.feature, packages/ripple-test-tools/step_definitions/components/index.js
=> Fix DemoLandingPage test

renovate.json
cheerio new version will introduce some issues on markup component, so we don't want to update it automatically.
1. Updated renovate config to ignore cheerio
=> Updated renovate config to ignore cheerio

packages/ripple-nuxt-tide/lib/core/logger.js, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/lib/server-middleware/request-log.js
This fixes an issue with application logs not being aggregated on the new Azure cluster.
=> Updated log client to read environment variables with sane defaults.

packages/components/Organisms/CampaignPrimary/CampaignPrimary.stories.mdx, packages/components/Organisms/CampaignPrimary/index.vue, packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx, packages/components/Organisms/CampaignSecondary/index.vue, packages/components/Organisms/HeroBanner/IntroBanner.vue, packages/components/Organisms/HeroBanner/heroBanner.stories.mdx
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5042
1. Added styling for anchor links in description field
=> [SDPA-5042] Add styling for anchor links in description field

packages/components/Molecules/Form/index.vue, packages/components/Molecules/Search/SearchForm.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5049
1. Automatically submit search form when clear filter button is used.
=> [SDPA-5049] : Automatically submit search form when filter is cleared

CONTRIBUTING.md, packages/components/Molecules/Card/Card.stories.mdx, packages/components/Molecules/Card/__test__/CardNav.test.js, packages/components/Molecules/Card/__test__/CardPromo.test.js, packages/components/Molecules/EmbeddedVideo/EmbeddedVideo.stories.mdx, packages/components/Molecules/EmbeddedVideo/index.vue, packages/components/Molecules/Figure/Figure.stories.mdx, packages/components/Molecules/Search/Search.stories.mdx, packages/components/Molecules/Timeline/Timeline.stories.mdx, packages/components/Organisms/CallToAction/CallToAction.stories.mdx, packages/components/Organisms/CampaignPrimary/CampaignPrimary.stories.mdx, packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx, packages/components/Organisms/Event/Event.stories.mdx, packages/components/Organisms/Grants/Grants.stories.mdx, packages/components/Organisms/Grants/GrantsOverview.vue, packages/components/Organisms/ImageGallery/ComplexImage.stories.mdx, packages/components/Organisms/ImageGallery/ImageGallery.stories.mdx, packages/components/Organisms/Markup/Markup.stories.mdx, packages/components/Organisms/News/News.stories.mdx, packages/components/Organisms/Profile/Profile.stories.mdx, packages/components/Organisms/SiteFooter/SiteFooter.stories.mdx
1. Use chromatic ignore element data attribute to ignore those dynamic visual element in visual testing
=> Fixed UI tests by ignoring dynamic stories

packages/create-ripple-app/template/nuxt/.eslintrc.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-2753
1.
=> [SDPSUP-2753] Updated create-ripple-app template

packages/ripple-nuxt-ui/README.md
**issue:** https://github.com/dpc-sdp/ripple/issues/922
1. Fixed grammar in README
=> Fixed grammar

renovate.json
**issue:** https://github.com/dpc-sdp/ripple/issues/887
1. Fixed incorrect renovate config
=> fix: fixed renovate configs

examples/vic-gov-au/test/e2e/plugins/index.js, packages/ripple-test-tools/step_definitions/common/global.js
1. Migrate cypress audit to new version
=> Fixed audit module changes

packages/ripple-nuxt-tide/lib/module.js
=> [SW-896] Transpile requrl that's causing IE11 bug

CONTRIBUTING.md
=> Fixed an incorrect docs

packages/components/Organisms/Markup/Markup.stories.mdx
1. Visual testing picks this broken image which failed the test on all PR. Fix it by replace the CMS image to placeholder one.
=> Fixed broken image in storybook

packages/ripple-nuxt-tide/modules/event/pages/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5159
1. Check if address exists in the event in addition to address length.
=> [SDPA-5159] Fix event card no location page error issue

packages/components/Organisms/SiteHeader/menu.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4913
1. Scroll to the top of the menu when a new menu is opened in the SiteHeader only in Mobile view
=> [SDPA-4913] Fix SiteHeader Menu Scroll Issue

packages/ripple-nuxt-tide/package.json, renovate.json, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5279
1.
=> [SDPA-5279] Upgrade cheerio dependency

.circleci/config.yml
=> Remove audit from commit CI step

.circleci/config.yml
=> Chromatic should exit zero in CI

packages/ripple-nuxt-tide/lib/middleware/misc.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5258
1. Updated to handle the new structure change in the api for metatag property. (Check the ticket for more details)
BE test pr - 
https://nginx-php.pr-1160.content-vic.sdp2.sdp.vic.gov.au/
=> [SDPA-5258] Updated metatag to handle the structure change for metatag property in JSON.

examples/vic-gov-au/test/e2e/integration/smoke/DemoLandingPage.feature, packages/ripple-nuxt-tide/modules/news/tide.config.js, packages/ripple-test-tools/step_definitions/components/index.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5342
1. Clean up featured news mapping as it is removed in BE
**Note**
This needs to be released along with https://digital-engagement.atlassian.net/browse/SDPA-5151
=> [SDPA-5342] Remove featured news mapping as it is removed in BE

packages/components/Molecules/PublishDateAndAuthor/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5254
1. Changed date/time format to produce output such as `Friday 28 May 2021 9:00am`.
Context discussion:
https://digital-engagement.atlassian.net/browse/SDPA-5208?focusedCommentId=132868
=> [SDPA-5254] Changed date format for `ripple-publish-date-and-author` component.

examples/vue-example-app/test/e2e/integration/smoke/ripple/step_definition.js
1. Updated old reference to card navigation class name for smoke test to pass.
=> Fix old reference to card navigation

packages/components/Molecules/ShareThis/__test__/ShareThis.test.js, packages/components/Molecules/ShareThis/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SRM-93
1. Fixed brand label to have proper capitalisation
=> [SRM-93] Fix brand label to have proper capitalisation

packages/components/Organisms/SiteHeader/index.vue
I noticed the documentation for the site-header properties doesn't describe the appropriate values to set for the `object` or `array`, which meant developers had to infer it from the examples and reading the code. After a discussion with @tim-yao, I've updated the documentation to include this information. I also added documentation for some of the simple properties too.
**JIRA issue:** There's no jira issue
1. I've added some documentation to the properties for the site header.
Before:
After:
There are no new tests since this PR is comments only. However, I did confirm that:
1. All tests still pass.
2. All linting still passes.
3. The documentation I created renders correctly in the storybook (see screenshot).
- [] I have added tests to cover my changes (if not applicable, please state …
=> Improved documentation for site-header organism

packages/ripple-tide-search-api/README.md, packages/ripple-tide-search-api/controllers/search.js, packages/ripple-tide-search-api/index.js, packages/ripple-tide-search-api/services/tide-search.js
1. Added a new function to handle DSL queries that are POSTed with a body in JSON format to /search-api/v2/dsl
2. Added documentation explaining how to use the new functionality.
=> Added support for POST requests in Ripple Tide Search API

packages/components/Organisms/Accordion/Accordion.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5283
1. Added if statement to only expand accordion when itemOpen is true.
- Issue on [current storybook](https://www.ripple.sdp.vic.gov.au/?path=/story/organisms-accordion--accordion): when accordion is expanded, and then closed before expansion is complete, it becomes expanded with no text. 
- [Fixed issue](https://storybook.pr-1020.ripple.sdp2.sdp.vic.gov.au/?path=/story/organisms-accordion--accordion): should open and close without any flaws.
=> [SDPA-5283] Fix accordion animation

packages/components/Organisms/Markup/Markup.stories.mdx, packages/components/Organisms/Markup/Markup.vue
=> Revert "[SDPA-5217] ordered list spacing"

packages/components/Organisms/Markup/Markup.stories.mdx, packages/components/Organisms/Markup/Markup.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5217
1. Adding padding bottom for after each line
2. Padding top for first child.
3. adding ol and li 
- [ X] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)
=> [SDPA-5217] Ordering lists

packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5406
1. Removed the summary field mapping from the filter, so it does not match the summary field which is attached to the body field. The new changes in the BE has removed that field for news content type and from now all the summary field should reference to the single one which is field_landing_page_summary.
=> [SDPA-5406] Removed the summary field reference for news attached to the body field.

packages/components/Molecules/DataTable/DataTable.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5156
1. Updated styling based on Scenario 
https://digital-engagement.atlassian.net/browse/SDPA-5156?focusedCommentId=144636
and
https://digital-engagement.atlassian.net/browse/SDPA-5156?focusedCommentId=144640
mentioned in the ticket
2. Attached file in the Jira ticket "RPLTable Use Cases.pdf" contains 8 cases of which Scenario 6 and 7 required change
=> [SDPA-5156] Format issues with tables on smaller screens

packages/components/Organisms/Markup/Markup.vue
- Removes rpl_breakpoint height
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-3770
1. Removed max-height for rpl_breakpoint('m')
Before
After
=> [SDPSUP-3770] Fixed images not in full width.

packages/components/Molecules/Layout/BackToTop.vue
=> Fix for back to top id #1112

packages/components/Organisms/Accordion/Accordion.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-1133
1. Check that this.itemOpen is defined
Open Accordions in storyboook, check console for errors.
=> [SW-1133] Fix JS error when opening accordions

packages/components/Organisms/Profile/Profile.stories.mdx, packages/components/Organisms/Profile/ProfileHighlight.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5892
1. Set `flex-shrink: 0` to use dimensions as defined
Before:
After:
* Story added in storybook with test case as per jira issue
=> [SDPA-5892] Maintain 1:1 aspect on profile image

examples/reference/package.json, packages/ripple-tide-api/src/services/tide-api.js, packages/ripple-tide-api/src/services/tide-page.js, packages/ripple-tide-landing-page/index.js, packages/ripple-tide-landing-page/index.vue
=> [RPL2-11] Adds recursive mapping for objects to Tide API package

.lagoon.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SS-113
1. Set up ingresses for the CDN
=> [SS-113] Domains for reference site

packages/components/Molecules/Layout/BackToTop.vue, packages/components/Molecules/Layout/SkipLink.vue, packages/components/Organisms/SiteHeader/index.vue
1. Fix for Back to top button not working due to mismatching Id's 
2. Removes support for multiple back to top buttons.
=> [SRM-295] Revert addition of multiple skip links

packages/ripple-nuxt-tide/modules/landing-page/lib/content-collection.js
**JIRA issue:**
https://digital-engagement.atlassian.net/browse/SDPA-5961
https://digital-engagement.atlassian.net/browse/SDPA-5995
This implements the `interface.filters.defaultStyling` option to automatically set the classes on the exposed filters.
Previously, for filters to correctly display, classes would need to be set on the field manually,
```json
{
"interface": {
"filters": {
"defaultStyling": false,
"fields": [{
"type": "basic",
"options": {},
"additionalClasses": ["app-content-collection__form-col-3"]
}]
}
}
}
```
Classes that could be used include:
```
app-content-collection__form-col-full
app-content-collection__form-col-2
app-content-collection__form-col-3
app-content-collection__form-col-4
```
But now, setting `defaultStyling` to `true` will handle setting these classes …
=> Content Collection - filter defaultStyling implementation

examples/reference/nuxt.config.js
=> Update reference site ID

packages/ripple-nuxt-tide/modules/landing-page/components/ContentCollection.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5281
1. Use RplMarkup for description field.
Implemented as per request:
> There has been a request to make the description field a WYSIWYG field.
=> [SDPA-5281] Content Collection - Add RplMarkup support for description.

packages/components/Organisms/Markup/package.json, packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap, yarn.lock
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SW-1379
1. Rolled back cheerio from rc.10 to rc.2 to restore IE11 functionality
=> [SW-1379] - Roll back cheerio to rc.2 to restore IE11 functionality

src/static/css/openforms.css
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-4025
1. Added CSS to file to override changes that Ripple overrides
Form to fix
[What it should look like](https://au.openforms.com/Form/5da439c0-0ad3-4940-8063-277715fb56c0?of-url=https%3A%2F%2Fwww.vic.gov.au%2Fpreview%2Flanding_page%2Fe1b09982-de47-4335-a49e-4bb3ea247213%2Flatest%3Fsection%3D4&of-color=rgba(0,0,0,0))
[Fixed](https://www.vic.gov.au/preview/landing_page/e1b09982-de47-4335-a49e-4bb3ea247213/latest?section=4)
Tested with Google Chrome overrides, and subsequently on this page: https://www.vic.gov.au/preview/landing_page/e1b09982-de47-4335-a49e-4bb3ea247213/latest?section=4
=> [SDPSUP-4025] Fixed CSS for OpenForms with Ripple theme applied

.circleci/config.yml, lerna.json
=> Automatically publish to NPM on merge to master

.circleci/config.yml
=> Bump CI cache key

packages/components/Molecules/Card/Card.stories.mdx, packages/components/Molecules/Figure/Figure.stories.mdx, packages/components/Molecules/Search/Search.stories.mdx, packages/components/Molecules/Timeline/Timeline.stories.mdx, packages/components/Organisms/CallToAction/CallToAction.stories.mdx, packages/components/Organisms/CampaignPrimary/CampaignPrimary.stories.mdx, packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx, packages/components/Organisms/Event/Event.stories.mdx, packages/components/Organisms/ImageGallery/ComplexImage.stories.mdx, packages/components/Organisms/ImageGallery/ImageGallery.stories.mdx, packages/components/Organisms/LinkTiles/LinkTiles.stories.mdx, packages/components/Organisms/Markup/Markup.stories.mdx, packages/components/Organisms/News/News.stories.mdx, packages/components/Organisms/Profile/Profile.stories.mdx, packages/components/Organisms/SiteFooter/SiteFooter.stories.mdx, src/.storybook/preview.js, src/storybook-components/svgPlaceholder.js
=> Replace placeholder URLs

packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SRM-324
1. Fix regression for content rating form spacing
Before
After
=> [SRM-324] Fix content rating radio spacing

.circleci/config.yml
=> Adds prerelease NPM publish workflow

packages/components/Molecules/Form/Form.stories.mdx, packages/components/Molecules/Form/fields/fieldRploptionbutton.vue, packages/components/Molecules/Form/index.vue
Introducing a sustainable pattern for triggering a submit from a `vue-form-generator` field component - ie. submit on click in the case of `Rploptionbutton`.
1. Add submit listener to rpl-form
2. Add emitter on optionbutton (behind schema flag)
3. Add demo story
=> Trigger form submit from search component

packages/components/Molecules/Form/Checkbox.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-6116
1. Increased focus border width on checkbox to match radio, reduced w x h to compensate
=> [SDPA-6116] Increase focus border on checkbox to match radio

packages/components/Molecules/Card/CardContent.vue, packages/components/Molecules/Card/CardPromo.vue, packages/components/Molecules/Card/__test__/CardPromo.test.js, packages/ripple-nuxt-ui/lib/templates/plugin.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-6095
1. Added new feature flag to show / hide the rainbow stripe that appears on promo cards that don't have an image. If this feature flag does not exist in the nuxt config it will default to showing the rainbow stripe, which is  the current expected result.
2. Updated promo card unit test to work with the new setup
=> [SDPA-6095] - card rainbow feature flag

packages/ripple-nuxt-tide/lib/core/breadcrumbs.js, packages/ripple-nuxt-tide/test/unit/breadcrumbs.test.js
1. Ignore `/site-123` prefix when evaluating activePath in breadcrumbs. Fixes [SW-1615]
[SW-1615]: https://digital-engagement.atlassian.net/browse/SW-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SW-1615] Ignore site id when setting breadcrumbs

packages/ripple-nuxt-tide/lib/middleware/breadcrumbs.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-6302
1. Added check for page title in breadcrumbs middleware of `ripple-nuxt-tide`, to prevent it from running before a page title has been set
=> [SDPA-6302] Check for presence of title to prevent middleware running out of order

packages/ripple-nuxt-tide/modules/landing-page/lib/content-collection.js
=> Adds Elasticsearch 7 support to CC

examples/reference/nuxt.config.js, examples/reference/tide/tide.content-collection.js, packages/ripple-nuxt-tide/lib/module.js, packages/ripple-nuxt-tide/modules/landing-page/__tests__/content-collection.test.js, packages/ripple-nuxt-tide/modules/landing-page/lib/content-collection.js
1. Changes the default sort option for content collection to be simplified to just created date (or news date for news items). This is in line with backend changes to remove the option of selecting the sort options in the UI. 
2. To enable the previous behaviour you can override the contentCollection constructor and pass `internal.managedSort: true` option 
https://github.com/dpc-sdp/ripple/blob/6bcc0e1d179d18a024036d0c206a8c5a17c70a1a/packages/ripple-nuxt-tide/modules/landing-page/__tests__/content-collection.test.js#L57)
=> Change default sort option for content collection

examples/reference/nuxt.config.js, packages/ripple-nuxt-tide/lib/module.js
=> Move tideSearchApi to be enabled by default

packages/components/Atoms/Button/index.vue, packages/components/Atoms/Link/Link.vue, packages/ripple-nuxt-tide/lib/config/markup-plugins.js, packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler.html, packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-6264
1. Update markup transpiler to include the target attribute when tranpiling buttons that are links
2. Internal links that have a target set will now also open in a new tab
=> [SDPA-6264] - Fix wysiwyg button target not being set

packages/ripple-nuxt-tide/lib/core/tide.js, packages/ripple-nuxt-tide/test/unit/tide.test.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6094
1. Excluded root request `"/"` from trailing slash op
- Added a unit test for tide API request to `"/"`
=> [SDPAP-6094] Exclude root request from trailing slash fix

packages/ripple-nuxt-tide/lib/templates/plugin.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6348
1. Updated deprecated `req.connection` call to `req.socket`. Fixes #1182 (the linked solution uses the express call `req.secure` but the release notes for node v13 use `req.socket`)
=> [SDPAP-6348] Replace deprecated req call

examples/basic-examples/nuxt.config.js, examples/reference/nuxt.config.js, packages/create-ripple-app/template/nuxt/nuxt.config.js, packages/ripple-nuxt-tide/README.md, packages/ripple-nuxt-tide/lib/module.js
_As a content editor I don’t want my CMS preview pages indexed by search engines so the public can’t access non published pages._
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-5916
1. Updated robots.txt generation so it's part of ripple-nuxt-tide, this is opt in so existing sites can still manage their own robots.txt generation.
2. Updated list of excludedPaths to include preview urls, oauth urls and the share url.
Here's three screenshots showing robots.txt working with the three config options, i.e. boolean, object and array.
They all have `Disallow: '/'` because it's not production.
This has been tested in browser locally, still needs testing on 'staging'. Does this change need tests written?
=> [SDPAP-5916] Updated robots.txt generation so it's part of ripple-nuxt-tide, updated list of excludedPaths.

examples/reference/nuxt.config.js, packages/components/Molecules/AnchorLinks/index.vue, packages/components/Organisms/Accordion/Accordion.vue, packages/components/Organisms/Accordion/accordion.scss, packages/components/Organisms/Accordion/index.js, packages/ripple-nuxt-tide/lib/pages/Tide.vue
_This task was done and released in 1.40 [SDPAP-6190: Ability to create/use anchor links with accordions COMPLETED](https://digital-vic.atlassian.net/browse/SDPAP-6190), however the following considerations arose upon it’s completion and a further UI review [SDP-Core-Accordion Title On This Page](https://www.figma.com/file/rlFyJFk81WaffKYbUyAwKL/SDP-Core-Accordion-Title-On-This-Page?node-id=711%3A19300)_
The task at hand for this PR is reverting the changes from [https://github.com/dpc-sdp/ripple/pull/1206](https://github.com/dpc-sdp/ripple/pull/1206/files#diff-7b119b1ed23de04b90ed532a1bd4b72f8434aa75f69131470c82552d24d8a131)
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6370
1. Reverted changes in packages/components/Molecules/AnchorLinks/index.vue
2. Reverted changes in …
=> [SDPAP-6370] Removed most changes from PR 1206, updated accordion titles to h3s

Dockerfile.storybook, package.json, src/package.json
=> build: :mute: suppress storybook build logs in lagoon

packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6368
1. Add default id prefix to forms; One thing to note is the duplicate ID issue would still occur if the form is on the page more than once. Probably very unlikely here, but something does occur on other sites.
View prefixed form fields here: https://app.pr-1236.ripple.sdp4.sdp.vic.gov.au/sdpta-webforms-18-08-2022
=> fix(@dpc-sdp/ripple-form): add default id prefix to forms

examples/reference/.env
This reverts commit 033198a8fd8f5d2eb4c7a5d0f31ea7c8072afa2b.
=> Revert "env"

packages/ripple-nuxt-tide/modules/site/module.js
We need to support paged sitemaps.
**JIRA issue:** https://digital-vic.atlassian.net/browse/SW-2204
1. Forward query params in tide middleware so paginated sitemap pages can be returned.
https://app.pr-1244.ripple.sdp4.sdp.vic.gov.au/sitemap.xml
https://app.pr-1244.ripple.sdp4.sdp.vic.gov.au/sitemap.xml?page=1
https://app.pr-1244.ripple.sdp4.sdp.vic.gov.au/sitemap.xml?page=2
=> [SW-2204]: forward sitemap query params

packages/components/Molecules/Form/index.vue
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-4751
We've been investigating a memory leak in Ripple 1.31 where pods will gradually grow up to 4GB memory use before being killed and restarted by Kubernetes.
I've documented my findings further in the relevant support issue but it seems that this was caused by setting up the RplFormEventBus in a `created` lifecycle hook rather than `mounted`. Reverting this caused memory usage to go back down to reasonable levels under sustained load.
I'm not 100% certain of the reasoning behind this change but raising this PR for visibility.
=> [SDPSUP-4751] Memory leak in v1.31

packages/ripple-nuxt-tide/lib/config/markup-plugins.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6342
1. Updated markup plugin to return only the text if the `<a>` tag does not have the href attribute
**BE input**
**FE output**
=> [SDPAP-6342] Updated markup plugin to return text if the link tag does not have href.

packages/components/Molecules/Form/index.vue, packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue, packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js, packages/ripple-nuxt-tide/modules/webform/mixins/index.js
1. Fix honeypot field being added multiple times
2. Add check for HTMLInputElement value of honeypot field instead of vue form generator tracked value, which was not being updated when form is populated programatically
=> [SDPAP-6923] fix honeypot not catching flies

packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue, packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js, packages/ripple-nuxt-tide/modules/webform/mixins/index.js
The BE added a new feature where you can use the hidden field to create a confirmation message using token which will be sent by the Post Request Response to the FE. It adds the custom message in the notes field of response data. The reason it couldn't use the existing confirmation message field because that field doesn't know the token value which gets generated after the submission and the exisiting confirmation field sends out the field before form submission.
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6961
1. Returned the response data in webform mixin and used it to show the custom confirmation message with token value that returned from the webform post response by the BE.
=> [SDPAP-6961] Added changes to capture custom confirmation message using token for webforms.

packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7052
1. Add support for new back end response notes; i.e. status and response message
As the back-end won't be returning a real status code we need to parse it out of a `notes` field, we could potential move this logic up out of the the vue component, so that `postForm` returns `data` and extra info like `status` instead of just the data. I'm not sure there's any "custom" work that relies on the current API though  (https://github.com/dpc-sdp/ripple/blob/develop/packages/ripple-nuxt-tide/modules/webform/mixins/index.js#L11). 
REF: https://app.pr-1269.ripple.sdp4.sdp.vic.gov.au/esta-forms-testing
=> [SDPAP-7052] add support for new back end response notes

packages/create-ripple-app/template/nuxt/nuxt.config.js
1. Fixed the spelling for preview module. Whenever a new project created, this goes in and cause issues with preview and share link feature for new sites.
=> Updated ripple create app to fix preview spelling.

packages/components/Molecules/Form/index.vue, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7024
1. Added support for custom regex patterns added via the cms, this applies to the following fields: textarea, textfield, email, telephone, url
3. Add margin to error messages, so they don't join together
=> [SDPAP-7024] add regex support to webforms

packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx, packages/components/Organisms/CampaignSecondary/index.vue, packages/ripple-nuxt-tide/lib/config/tide.config.js, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js, packages/ripple-nuxt-tide/modules/profile/tide.config.js
…ity from secondary campaign banner
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-7121
After a backend change to remove the video functionality from the secondary campaign banner, the reference site broke because it was still expecting 'field_landing_page_c_secondary.field_block_embedded_video' to exist.
1. Removed includes for 'field_landing_page_c_secondary.field_block_embedded_video'
2. Removed unused video logic from secondary campaign banner
Checked visually that the secondary campaign banner is still functional
=> [SDPAP-7121] - Removed of "Campaign with video" functionality from secondary campaign

packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx, packages/components/Organisms/CampaignSecondary/index.vue, packages/ripple-nuxt-tide/lib/config/tide.config.js, packages/ripple-nuxt-tide/modules/landing-page/tide.config.js, packages/ripple-nuxt-tide/modules/profile/tide.config.js
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-7121
After a backend change to remove the video functionality from the secondary campaign banner, the reference site broke because it was still expecting 'field_landing_page_c_secondary.field_block_embedded_video' to exist.
1. Removed includes for 'field_landing_page_c_secondary.field_block_embedded_video'
2. Removed unused video logic from secondary campaign banner
Checked visually that the secondary campaign banner is still functional
=> [SDPAP-7121] - Removal of "Campaign with video" functionality from secondary campaign

packages/ripple-nuxt-tide/modules/site/module.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7462
- Update sitemap proxying to match the new format required (post drupal sitemaps plugin update). 
- Variants are no longer supported so we just have the one URL being proxied now.
=> [SDPAP-7462] update sitemap proxying

.circleci/config.yml
=> Disable failing integration tasks on release

packages/ripple-nuxt-tide/modules/landing-page/components/DataList.vue, packages/ripple-nuxt-tide/modules/landing-page/lib/data-list.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6808
1. Move getResultsFromMiddleware (it was only  part of the reference site)
=> feat(@dpc-sdp/ripple-nuxt-tide): move getResultsFromMiddleware function

packages/components/Molecules/Contact/Contact.stories.mdx, packages/components/Molecules/Contact/index.vue, packages/ripple-nuxt-tide/lib/core/mapping-filters.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7645
Updates for new custom website links added via CMS.
Our icons sizes are different so this has a custom 'scale'. 
Also the other social link names directly map to an icon. i.e. `twitter`, `facebook` etc, however the CMS field for this is understandably `website`, however we don't have a `website` icon so we need to map `website` to `browser`.
=> [SDPAP-7645] support for website links

packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7783
1. Adding support for conditional showing the submit button
=> [SDPAP-7783] add support for conditional submit

packages/ripple-nuxt-tide/modules/webform/components/TideForm.vue, packages/ripple-nuxt-tide/modules/webform/conditional-logic.js, packages/ripple-nuxt-tide/modules/webform/mapping-filters.js, packages/ripple-nuxt-tide/test/unit/webform.test.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7452
1. Clear fields when hidden by conditional logic
=> [SDPAP-7452] clear fields when hidden by conditional logic

packages/components/Organisms/Markup/Markup.vue
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7881
1. Llmit iframe max-width on xxl+ screens to the xl container width i.e. 1056px.
=> [SDPAP-7881] limit iframe max-width on xxl screens

packages/ripple-nuxt-tide/lib/core/tide-helper.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7850 
1. Update language field to use locale, the previous field was depricated
=> [SDPAP-8004] update language field to use locale

packages/components/Organisms/Markup/Markup.vue
=> [SDPAP-8044] update nested ol types

packages/components/Atoms/Global/scss/settings/_languages.scss, packages/ripple-nuxt-tide/lib/middleware/languages.js
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-8023
1. Add new font for Karenni/Kayah Li language
=> [SDPAP-8023] add new font for Karenni/Kayah Li language

.github/workflows/e2e.yml
1. Updated the E2E workflow to use the `biggy-ripple` runner.
=> update runner to new large instance

.lagoon.yml
=> Removed obsolete routes
